const sharedData = { 


  groupz: {
    "Basics": "łatwy",
    "Język & Komunikacja": "język liczby pieniądze",
    "Człowiek & Zdrowie": "życie praca_zawód medyczny",
    "Jedzenie & Picie": "jedzenie składniki zakupy",
    "Natura & Środowisko": "natura pogoda kamienie metale",
    "Wolny Czas & Styl Życia": "wychodzenie sport hobby ubrania muzyka tech",
    "Podróże & Transport": "podróże ruch drogowy samochód kosmos",
    "Dom & Mieszkanie": "relaks narzędzia",
    "Kultura & Społeczeństwo": "religia polityka instytucje_oficjalne"
  },
  categories: {
            "łatwy": "1_do_10 kolory zwierzęta owoce powitanie smaki",
            "liczby": "1_do_10 duże_liczby matematyka",
            "życie": "ludzie rodzina członkowie_rodziny ulica",
            "natura": "zwierzęta ptaki ryby drzewa rośliny stworzenia_morskie owady",
            "składniki": "warzywa owoce zioła przyprawy",
            "jedzenie": "smaki kuchnia kolacja śniadanie desery słodycze",
            "zakupy": "zakupy centrum_handlowe sklepik warung",
            "sport": "surfing piłka_nożna żeglowanie łódź morze_ocean",
            "pogoda": "rodzaje klimat",
            "relaks": "w_domu z_rodziną sauna terapia",
            "język": "powitanie rozmowa formalny nieformalny przyjaciele przyimki czasowniki",
            "ubrania": "elegancko zwykły wystrojony buty",
            "wychodzenie": "restauracja klubowanie koncert knajpa",
            "medyczny": "osoby budynek objawy dolegliwości części_ciała leki",
            "podróże": "lotnisko komunikacja_publiczna dworzec",
            "ruch_drogowy": "ulica rower samochody pieszy środek_transportu trasa przepisy",
            "pieniądze": "płatność_kartą płatność_gotówką konto kryptowaluty",
            "hobby": "zabawki gry_elektroniczne gry_planszowe kolory",
            "muzyka": "słuchanie instrumenty",
            "samochód": "wnętrze części",
            "praca_zawód": "praca",
            "narzędzia": "drewno w_pomieszczeniu na_zewnątrz ciężki_sprzęt",
            "kosmos": "planety gwiazdy zodiak",
            "metale": "metale",
            "kamienie": "kamienie kamienie_szlachetne",
            "polityka": "urzędnicy",
            "instytucje_oficjalne": "ratusz komisariat_policji kościół",
            "religia": "islam protestantyzm katolicyzm hinduizm buddyzm konfucjanizm",
            "tech": "komputer wideo audio hi-fi telewizja filmy"
        },

   wordLists: {
            "ludzie": [
                ["ja", "ik"],
                ["ty", "jij"],
                ["on", "hij"],
                ["ona", "zij (meisje)"],
                ["my (bez ciebie)", "wij(zonder jou)"],
                ["my (z tobą)", "wij(met jou)"],
                ["wy", "jullie"],
                ["oni/one", "zij (groep)"],
                ["przyjaciel", "vriend"],
                ["rodzina", "familie"],
                ["matka", "moeder"],
                ["ojciec", "vader"],
                ["Pan/Pani", "U"]
            ],

        "rodzina": [
    ["dziadek", "opa"],
    ["babcia", "oma"],
    ["ojciec", "vader"],
    ["matka", "moeder"],
    ["brat", "broer"],
    ["siostra", "zus"],
    ["syn", "zoon"],
    ["córka", "dochter"],
    ["wujek", "oom"],
    ["dziecko", "kind"],
    ["ciotka", "tante"],
    ["kuzyn", "neef"],
    ["kuzynka", "nicht"]
],
"członkowie_rodziny": [
    ["dziadek", "grootvader"],
    ["babcia", "grootmoeder"],
    ["wnuk", "kleinzoon"],
    ["wnuczka", "kleindochter"],
    ["teść", "schoonvader"],
    ["teściowa", "schoonmoeder"],
    ["szwagier", "zwager"],
    ["szwagierka", "schoonzus"],
    ["szwagier", "schoonbroer"],
    ["szwagierka", "schoonzus"],
    ["wujek stryjeczny / pradziadek wujek", "achteroom"],
    ["daleka kuzynka", "achternicht"],
    ["siostrzeniec / bratanek mały", "neefje"],
    ["siostrzenica / bratanica mała", "nichtje"],
    ["rodzina teściów", "schoonfamilie"],
    ["rodzina", "familie"],
    ["krewny", "verwant"]
],

"kamienie": [
    ["kamień", "steen"],
    ["skała", "rots"],
    ["głaz / otoczak", "kei"],
    ["żwir", "grind"],
    ["piaskowiec", "zandsteen"],
    ["wapień", "kalksteen"],
    ["granit", "graniet"],
    ["marmur", "marmer"],
    ["łupkowy / łupki", "leisteen"],
    ["bazalt", "basalt"],
    ["lawa", "lava"],
    ["pumeks", "puimsteen"],
    ["glina", "klei"],
    ["kryształ", "kristal"],
    ["ruda / minerał", "erts"]
],
"kamienie_szlachetne": [
    ["diament", "diamant"],
    ["brylant", "briljant"],
    ["rubin", "robijn"],
    ["szafir", "saffier"],
    ["szmaragd", "emerald"],
    ["szmaragd", "smaragd"],
    ["ametyst", "amethist"],
    ["topaz", "topaas"],
    ["turmalin", "toermalijn"],
    ["akwamaryn", "aquamarijn"],
    ["granat", "granaat"],
    ["opal", "opaal"],
    ["perydot", "peridoot"],
    ["cytryn", "citrine"],
    ["turkus", "turkoois"]
],

            "powitanie": [
                ["cześć", "hallo"],
                ["dzień dobry", "goeie morgen"],
                ["dobry wieczór / dobre popołudnie", "goeie middag"],
                ["dobranoc", "goeie avond"],
                ["do widzenia", "tot ziens"],
                ["dziękuję", "dank je"],
                ["nie ma za co", "graag gedaan (bali)"],
                ["nie ma problemu", "graag gedaan (java)"],
                ["co słychać?", "hoe is het"],
                ["spokojnie", "relax"],
                ["normalnie", "gewoon"],
                ["nie trzeba", "geen gedoe"],
                ["jak się masz?", "hoe is het met jou"]
            ],
            "rozmowa": [
                ["co słychać?", "Hoe gaat het?"],
                ["dawno się nie widzieliśmy!", "Lang niet gezien!"],
                ["co u ciebie słychać teraz?", "Wat doe jij tegenwoordig?"],
                ["jak twoja rodzina?", "Hoe is het met je familie?"],
                ["do widzenia!", "Tot ziens!"],
                ["dbaj o siebie!", "Doe voorzichtig!"],
                ["powodzenia!", "Succes ermee!"],
                ["miło cię widzieć!", "Leuk je te zien!"],
                ["do zobaczenia wkrótce!", "Tot snel!"],
                ["uważaj!", "Pas op!"],
                ["gratulacje!", "Gefeliciteerd!"],
                ["przepraszam, moja wina!", "Sorry, mijn fout!"]
            ],
            "ulica": [
                ["uważaj na samochód!", "Pas op voor de auto!"],
                ["możesz się na chwilę przesunąć?", "Kun je even opzij gaan?"],
                ["gdzie jest przystanek?", "Waar is de halte?"],
                ["mogę przejść?", "Mag ik erlangs?"],
                ["uważaj na rower!", "Kijk uit voor de fiets!"],
                ["tu jest tłoczno!", "Het is hier druk!"],
                ["poczekaj na zielone!", "Wacht even op groen!"],
                ["nie przechodź tędy!", "Niet oversteken hier!"],
                ["w lewo", "Linksaf"],
                ["w prawo", "rechtsaf"],
                ["prosto", "Rechtdoor"],
                ["czy to właściwa strona?", "Is dit de goede kant?"],
                ["spokojnie / powoli!", "Rustig aan!"]
            ],

    "przyimki": [
    ["w", "aan"],
    ["za", "achter"],
    ["od", "af"],
    ["oprócz", "behalve"],
    ["pod", "beneden"],
    ["przy / u / z", "bij"],
    ["w środku / wewnątrz", "binnen"],
    ["nad", "boven"],
    ["na zewnątrz", "buiten"],
    ["przez", "door"],
    ["w", "in"],
    ["wzdłuż", "langs"],
    ["z", "met"],
    ["po", "na"],
    ["do", "naar"],
    ["obok", "naast"],
    ["około / o", "om"],
    ["pod", "onder"],
    ["na", "op"],
    ["o / nad", "over"],
    ["przez", "per"],
    ["od", "sinds"],
    ["w / do", "te"],
    ["przeciwko", "tegen"],
    ["do", "tot"],
    ["z / od", "uit"],
    ["z / od", "van"],
    ["dla / przed", "voor"],
    ["między", "tussen"],
    ["bez", "zonder"]
],
"czasowniki": [
    ["być", "zijn"],
    ["mieć", "hebben"],
    ["robić", "doen"],
    ["iść / jechać", "gaan"],
    ["przychodzić / przybywać", "komen"],
    ["chcieć", "willen"],
    ["móc", "kunnen"],
    ["mówić / powiedzieć", "zeggen"],
    ["robić / tworzyć", "maken"],
    ["patrzeć / oglądać", "kijken"],
    ["pytać", "vragen"],
    ["wiedzieć", "weten"],
    ["musieć", "moeten"],
    ["pracować", "werken"],
    ["jeść", "eten"],
    ["pić", "drinken"],
    ["widzieć", "zien"],
    ["znajdować / uważać", "vinden"],
    ["dawać", "geven"],
    ["brać / wziąć", "nemen"],
    ["zaczynać", "beginnen"],
    ["kończyć", "eindigen"],
    ["mówić / przemawiać", "spreken"],
    ["rozmawiać", "praten"],
    ["czytać", "lezen"],
    ["pisać", "schrijven"],
    ["pomagać", "helpen"],
    ["uczyć się", "leren"],
    ["mieszkać", "wonen"],
    ["spać", "slapen"]
],

    "osoby": [
                ["lekarz / doktor", "doktor"],
                ["pielęgniarka", "verpleegster"],
                ["chirurg", "chirurg"],
                ["pacjent", "patient"],
                ["dentysta", "tandarts"],
                ["fizjoterapeuta", "fysio"],
                ["farmaceut / aptekarz", "apotheker"],
                ["masażysta", "masseur"],
                ["anestezjolog", "anesthesist"]
            ],
            "zwierzęta": [
                ["pies", "hond"],
                ["kot", "kat"],
                ["królik", "konijn"],
                ["koń", "paard"],
                ["krowa", "koe"],
                ["świnia", "varken"],
                ["owca", "schaap"],
                ["ryba", "vis"],
                ["kura / kurczak", "kip"],
                ["słoń", "olifant"],
                ["tygrys", "tijger"],
                ["małpa", "aap"],
                ["lew", "leeuw"]
            ],
            "ryby": [
                ["okoń", "baars"],
                ["szczupak", "snoek"],
                ["karp", "karper"],
                ["węgorz", "paling"],
                ["sandacz", "snoekbaars"],
                ["płoć", "voorn"],
                ["leszcz", "brasem"],
                ["milkfish / chanos", "melkvis"],
                ["sum", "meerval"],
                ["olbrzymi gurami", "reuzengurami"],
                ["tilapia", "tilapia"],
                ["makrela indyjska", "Indische makreel"]
            ],
            "ptaki": [
                ["sikorka czubatka / bogatka", "koolmees"],
                ["modraszka", "pimpelmees"],
                ["wróbel zwyczajny", "huismus"],
                ["rudzik", "roodborst"],
                ["sroka", "ekster"],
                ["gołąb grzywacz", "houtduif"],
                ["kos", "merel"],
                ["wróbel", "mus"],
                ["strzyżyk", "winterkoning"],
                ["gołąb", "duif"]
            ],
            "stworzenia_morskie": [
                ["foka", "zeehond"],
                ["krab", "krab"],
                ["krewetka / garnał", "garnaal"],
                ["rozgwiazda", "zeester"],
                ["meduza", "kwal"],
                ["małż kokle", "kokkel"],
                ["małż / omułek", "mossel"],
                ["żółw zielony", "groene zeeschildpad"],
                ["żółw karetta", "karetschildpad"],
                ["dugong", "doegong"],
                ["manta olbrzymia", "reuzenmanta"],
                ["rekin wielorybi", "walvishaai"]
            ],
            "owady": [
                ["biedronka", "lieveheersbeestje"],
                ["trzmiel", "hommel"],
                ["pszczoła miodna", "bij"],
                ["osa", "wesp"],
                ["mucha domowa", "huisvlieg"],
                ["bzygowate / muchówka", "zweefvlieg"],
                ["szczypawka", "oorworm"],
                ["ważka", "libelle"],
                ["karaluch", "kakkerlak"],
                ["komar", "mug"],
                ["mrówka", "mier"],
                ["motyl", "vlinder"]
            ],

    "owoce": [
                ["jabłko", "appel"],
                ["banan", "banaan"],
                ["pomarańcza", "sinaasappel"],
                ["truskawka", "aardbei"],
                ["gruszka", "peer"],
                ["winogrono", "druif"],
                ["wiśnia / czereśnia", "kers"],
                ["ananas", "ananas"],
                ["mango", "mango"],
                ["cytryna", "citroen"],
                ["limonka", "limoen"],
                ["melon", "meloen"]
             ],
             "zioła": [
                ["bazylia", "basilicum"],
                ["kolendra", "koriander"],
                ["mięta", "munt"],
                ["koper", "dille"],
                ["tymianek", "tijm"],
                ["rozmaryn", "rozemarijn"],
                ["szałwia", "salie"],
                ["estragon", "dragon"],
                ["szczypiorek", "bieslook"],
                ["trawa cytrynowa", "citroen gras"],
                ["oregano", "oregano"],
                ["liść laurowy", "laurier"]
             ],
             "warzywa": [
                ["marchew", "wortel"],
                ["cebula", "ui"],
                ["pomidor", "tomaat"],
                ["sałata", "sla"],
                ["ogórek", "komkommer"],
                ["ziemniak", "aardappel"],
                ["kalafior", "bloemkool"],
                ["brokuł", "broccoli"],
                ["szpinak", "spinazie"],
                ["czosnek", "knoflook"],
                ["papryka", "paprika"],
                ["cukinia", "courgette"]
             ],
    "przyprawy": [
                ["cynamon", "kaneel"],
                ["goździk", "kruidnagel"],
                ["gałka muszkatołowa", "nootmuskaat"],
                ["imbir", "gember"],
                ["kurkuma", "kurkuma"],
                ["kmin rzymski", "komijn"],
                ["kardamon", "kardemom"],
                ["pieprz", "peper"],
                ["anyż gwiazdkowaty", "anijs"],
                ["macis / kwiat muszkatołowy", "foelie"],
                ["szafran", "saffraan"],
                ["nasiona kolendry", "korianderzaad"]
             ],
            "kolory": [
                ["czerwony", "rood"],
                ["czarny", "zwart"],
                ["kolor", "kleur"],
                ["niebieski", "blauw"],
                ["biały", "wit"],
                ["pomarańczowy", "oranje"],
                ["fioletowy", "paars"],
                ["różowy", "roze"],
                ["zielony", "groen"],
                ["żółty", "geel"],
                ["brązowy", "bruin"],
                ["szary", "grijs"]
            ],
            "exotic": [
                ["turkusowy", "turquoise"],
                ["liliowy", "lila"],
                ["magenta", "magenta"],
                ["indygo", "indigo"],
                ["ciemny fioletowy", "paars"],
                ["fuksja", "fuchsia"],
                ["cyjan", "cyaan"],
                ["kobaltowy niebieski", "kobaltblauw"],
                ["szafirowy", "saffier"],
                ["ametystowy", "amethist"],
                ["szmaragdowy", "smaragd"],
                ["koralowy róż", "roze koraal"]
            ],

    "rośliny": [
                ["mniszek lekarski / dmuchawiec", "paardebloem"],
                ["pelargonia", "geranium"],
                ["słonecznik", "zonnebloem"],
                ["złocień / jaskier", "boterbloem"],
                ["jaśmin", "jasmijn"],
                ["hibiskus", "hibiscus"],
                ["frangipani / plumeria", "frangipani/plumeria"],
                ["bugenwilla", "bougainville"],
                ["ixora", "ixora"],
                ["róża", "roos"],
                ["chryzantema", "chrysant"]
            ],
            "drzewa": [
                ["drzewo", "boom"],
                ["dąb", "eik"],
                ["buk", "beuk"],
                ["sosna", "den"],
                ["jodła / świerk", "spar"],
                ["brzoza", "berk"],
                ["klon", "esdoorn"],
                ["kasztanowiec", "kastanje"],
                ["wierzba", "wilg"],
                ["lipa", "linde"],
                ["topola", "populier"],
                ["palma", "palm"]
            ],
            "budynek": [
                ["szpital", "ziekenhuis"],
                ["klinika", "kliniek"],
                ["gabinet lekarski", "dokterpraktijk"],
                ["apteka", "apotheek"],
                ["izba przyjęć / SOR", "spoedeisende hulp"],
                ["przychodnia / poliklinika", "polikliniek"],
                ["laboratorium", "laboratorium"],
                ["oddział rentgenowski", "röntgenafdeling"],
                ["sala operacyjna", "operatiekamer"],
                ["poczekalnia", "wachtkamer"],
                ["oddział dziecięcy", "kinderafdeling"],
                ["sala porodowa", "verloskamer"]
            ],
            "objawy": [
                ["gorączka", "koorts"],
                ["ból głowy", "hoofdpijn"],
                ["kaszel", "hoesten"],
                ["ból gardła", "keelpijn"],
                ["nudności", "misselijk"],
                ["wymioty", "braken"],
                ["biegunka", "diarree"],
                ["zaparcia", "verstopping"],
                ["zawroty głowy", "duizelig"],
                ["duszność", "kortademig"],
                ["zmęczony", "moe"],
                ["pocenie się", "zweten"]
            ],
            "dolegliwości": [
                ["ból", "pijn"],
                ["swędzenie", "jeuk"],
                ["obrzęk", "zwelling"],
                ["krwawienie", "bloeding"],
                ["wysypka", "uitslag"],
                ["sztywność", "stijf"],
                ["słabość", "zwak"],
                ["oddychanie", "ademhaling"],
                ["kołatanie serca", "hartkloppingen"],
                ["uczucie pieczenia", "brandend gevoel"],
                ["ucisk w klatce piersiowej", "druk op de borst"],
                ["mrowienie", "tintelingen"],
                ["skurcz", "kramp"]
            ],
            "leki": [
                ["paracetamol", "paracetamol"],
                ["ibuprofen", "ibuprofen"],
                ["amoksycylina", "amoxicilline"],
                ["środek przeciwbólowy", "pijnstiller"],
                ["antybiotyk", "antibiotica"],
                ["syrop na kaszel", "hoestsiroop"],
                ["witamina", "vitamine"],
                ["plaster / opatrunek", "pleister"],
                ["maść", "zalf"],
                ["tabletki", "tabletten"],
                ["zastrzyk", "injectie"],
                ["krople", "druppels"]
            ],

    "części_ciała": [
                ["części ciała", "lichaamsdelen"],
                ["ręka", "hand"],
                ["stopa", "voet"],
                ["ramię", "arm"],
                ["noga (włącznie ze stopą)", "been (incl. voet)"],
                ["noga (bez stopy)", "been (excl. voet)"],
                ["palec", "vinger"],
                ["palec u nogi", "teen"],
                ["głowa", "hoofd"],
                ["szyja", "hals"],
                ["nos", "neus"],
                ["brzuch", "buik"],
                ["klatka piersiowa / pierś", "borst"],
                ["łokieć", "elleboog"],
                ["łydka", "kuit"],
                ["ucho", "oor"],
                ["usta", "mond"],
                ["język", "tong"],
                ["nadgarstek", "pols"],
                ["ramię / bark", "schouder"],
                ["kostka", "enkel"],
                ["kolano", "knie"]
            ],
            "lotnisko": [
                ["lotnisko", "vliegveld"],
                ["samolot", "vliegtuig"],
                ["odprawa", "check-in"],
                ["bagaż", "bagage"],
                ["palarnia", "rookruimte"],
                ["paszport", "paspoort"],
                ["bramka / gate", "gate"],
                ["odloty", "vertrek"],
                ["przyloty", "aankomst"],
                ["cło", "douane"],
                ["kontrola bezpieczeństwa", "veiligheidscontrole"],
                ["karta pokładowa", "boarding pass"],
                ["poczekalnia", "wachtruimte"],
                ["stewardessa", "stewardes"],
                ["steward", "steward"],
                ["bezcłowy / duty free", "belasting vrij"],
                ["taśma bagażowa", "bagageband"]
            ],
            "komunikacja_publiczna": [
                ["transport publiczny", "openbaar vervoer"],
                ["autobus", "bus"],
                ["tramwaj", "tram"],
                ["metro", "metro"],
                ["przystanek", "halte"],
                ["bilet", "kaartje"],
                ["kierowca", "chauffeur"],
                ["przystanek", "halteplaats"],
                ["linia", "lijn"],
                ["bilet powrotny", "retour"],
                ["abonament", "abonnement"],
                ["przesiadka", "omwisselen"]
            ],
            "dworzec": [
                ["stacja", "station"],
                ["pociąg", "trein"],
                ["peron", "perron"],
                ["bilet kolejowy", "treinkaartje"],
                ["tor", "spoor"],
                ["kasa", "loket"],
                ["godzina odjazdu", "vertrektijd"],
                ["godzina przyjazdu", "aankomsttijd"],
                ["kolej", "spoorweg"],
                ["przechowalnia bagażu", "bagagekluis"],
                ["informacja", "informatiebalie"],
                ["przesiadka", "overstap"]
            ],
            "smaki": [
                ["smaki", "smaken"],
                ["słodki", "zoet"],
                ["słony", "zout"],
                ["kwaśny", "zuur"],
                ["gorzki", "bitter"],
                ["ostry / pikantny", "pittig/scherp"],
                ["pikantny", "pikant"],
                ["aromatyczny / przyprawiony", "kruidig"],
                ["świeży", "fris"],
                ["miękki / delikatny", "zacht"],
                ["kremowy", "romig"],
                ["wytrawny", "hartig"],
                ["cierpki", "wrang"]
            ],
            "kuchnia": [
                ["kuchnia", "keuken"],
                ["gotować", "koken"],
                ["przepis", "recept"],
                ["garnek", "pan"],
                ["patelnia", "koekenpan"],
                ["piekarnik", "oven"],
                ["kroić", "snijden"],
                ["mieszać", "roeren"],
                ["smażyć / piec", "bakken"],
                ["gotować (gotować na wrzątku)", "koken"],
                ["przyprawy", "kruiden"],
                ["sól", "zout"],
                ["pieprz", "peper"]
            ],
    "restauracja": [
                ["restauracja", "restaurant"],
                ["menu", "menu"],
                ["kelner", "ober"],
                ["zamawiać", "bestellen"],
                ["rachunek", "rekening"],
                ["napiwek", "fooi"],
                ["stół", "tafel"],
                ["krzesło", "stoel"],
                ["karta menu", "kaart"],
                ["rezerwować", "reserveren"],
                ["na wynos", "afhalen"],
                ["serwować", "serveren"]
            ],
            "kolacja": [
                ["kolacja", "dinner"],
                ["danie główne", "hoofdgerecht"],
                ["dodatek / przystawka", "bijgerecht"],
                ["zupa", "soep"],
                ["sałatka", "salade"],
                ["ryż", "rijst"],
                ["mięso", "vlees"],
                ["ryba", "vis"],
                ["warzywa", "groente"],
                ["sos", "saus"],
                ["jeść", "eten"],
                ["cieszyć się", "genieten"]
            ],
            "śniadanie": [
                ["śniadanie", "ontbijt"],
                ["chleb", "brood"],
                ["masło", "boter"],
                ["ser", "kaas"],
                ["jajko", "ei"],
                ["dżem", "jam"],
                ["kawa", "koffie"],
                ["herbata", "thee"],
                ["croissant", "croissant"],
                ["jogurt", "yoghurt"],
                ["musli / granola", "muesli"],
                ["naleśnik / placuszek", "pannenkoek"]
            ],

    "desery": [
                ["desery", "toetjes"],
                ["deser", "toetje"],
                ["lody", "ijs"],
                ["budyń", "pudding"],
                ["tort", "taart"],
                ["ciasto", "cake"],
                ["czekolada", "chocolade"],
                ["owoce", "fruit"],
                ["jogurt", "yoghurt"],
                ["flan / karmel", "flan"],
                ["crème brûlée", "crème brûlée"],
                ["tiramisu", "tiramisu"],
                ["ciastka / wypieki", "gebak"]
            ],
            "słodycze": [
                ["słodycze", "snoep"],
                ["cukierki / słodycze", "snoep"],
                ["czekolada", "chocolade"],
                ["lukrecja / kwaśne cukierki", "drop"],
                ["guma do żucia", "gom"],
                ["lizak", "lolly"],
                ["marshmallow", "marshmallow"],
                ["miśki żelowe / gumisie", "gummybeer"],
                ["kwaśny cukierek", "zuurtje"],
                ["toffi / miękkie karmelki", "toffees"],
                ["miętowy cukierek", "pepermunt"],
                ["guma do żucia", "kauwgom"],
                ["kwaśne cukierki", "zuurtjes"]
            ],
            "płatność_kartą": [
                ["płatności kartą", "betaal_pin"],
                ["płacić kartą", "pinnen"],
                ["kod PIN", "pincode"],
                ["karta", "pasje"],
                ["bankomat", "automaat"],
                ["saldo", "saldo"],
                ["wpisać / wprowadzić", "intoetsen"],
                ["wypłacić gotówkę", "opnemen"],
                ["chip", "chip"],
                ["bezstykowy / zbliżeniowy", "contactloos"],
                ["limit", "limiet"],
                ["potwierdzić", "bevestigen"],
                ["płacić", "betalen"],
                ["cena", "prijs"],
                ["transakcja", "transactie"],
                ["koszty / opłaty", "kosten"]
            ],
    "płatność_gotówką": [
                ["płatności gotówką", "betaal_cash"],
                ["gotówka", "contant"],
                ["pieniądze", "geld"],
                ["banknot", "briefje"],
                ["monety", "munten"],
                ["reszta", "wisselgeld"],
                ["płacić", "betalen"],
                ["kasa", "kassa"],
                ["portfel", "portemonnee"],
                ["100 euro", "100 euro"],
                ["napiwek", "fooi"],
                ["karta czy gotówka?", "pinnen of cash?"],
                ["cena", "prijs"],
                ["zniżka", "korting"],
                ["drobne / drobniaki", "kleingeld"]
            ],
            "konto": [
                ["konto", "rekening"],
                ["konto bankowe", "bankrekening"],
                ["konto oszczędnościowe", "spaarrekening"],
                ["konto bieżące", "betaalrekening"],
                ["odsetki", "rente"],
                ["saldo", "saldo"],
                ["przelew", "overschrijving"],
                ["inkaso / polecenie zapłaty", "incasso"],
                ["wyciąg bankowy", "afschrift"],
                ["IBAN", "IBAN"],
                ["BIC / SWIFT", "BIC"],
                ["opłaty / prowizje", "kosten"]
            ],
            "kryptowaluty": [
                ["kryptowaluty", "crypto"],
                ["kryptowaluta", "cryptocurrency"],
                ["bitcoin", "bitcoin"],
                ["ethereum", "ethereum"],
                ["portfel kryptowalutowy", "wallet"],
                ["giełda / exchange", "exchange"],
                ["blockchain", "blockchain"],
                ["mining / kopanie", "mining"],
                ["kurs", "koers"],
                ["token", "token"],
                ["klucz prywatny", "private key"],
                ["fraza odzyskiwania / seed phrase", "seed phrase"],
                ["staking", "staking"]
            ],

    "rower": [
                ["rower", "fiets"],
                ["rowery", "fietsen"],
                ["kolarz / rowerzysta", "fietser"],
                ["kask rowerowy / kask na rower", "fietshelm"],
                ["dzwonek rowerowy", "fietsbel"],
                ["ścieżka rowerowa", "fietspad"],
                ["przebita opona / guma", "band lek"],
                ["pompa", "pomp"],
                ["zamek / kłódka rowerowa", "slot"],
                ["bagażnik rowerowy", "bagagedrager"],
                ["lampka rowerowa", "fietslamp"],
                ["siodełko", "zadel"]
            ],
            "samochody": [
                ["samochody", "autos"],
                ["samochód", "auto"],
                ["prowadzić / jechać samochodem", "rijden"],
                ["kierowca", "chauffeur"],
                ["benzyna", "benzine"],
                ["diesel", "diesel"],
                ["parkować", "parkeren"],
                ["kierownica", "stuur"],
                ["hamulec", "rem"],
                ["pedał gazu", "gaspedaal"],
                ["sprzęgło", "koppeling"],
                ["bagażnik", "kofferbak"],
                ["okno", "raam"]
            ],
            "pieszy": [
                ["pieszy", "voetganger"],
                ["chodzić / iść pieszo", "lopen"],
                ["zebra / przejście dla pieszych", "zebrapad"],
                ["chodnik", "stoep"],
                ["przejście dla pieszych", "oversteekplaats"],
                ["sygnalizacja świetlna", "verkeerslicht"],
                ["czerwone światło", "rood licht"],
                ["zielone światło", "groen licht"],
                ["przechodzić", "oversteken"],
                ["chodnik", "trottoir"],
                ["ścieżka dla pieszych", "voetpad"]
            ],
            "środek_transportu": [
                ["środki transportu", "vvmiddel"],
                ["pojazd", "voertuig"],
                ["skuter / motorower", "bromfiets"],
                ["motocykl", "motor"],
                ["samochód", "auto"],
                ["rower", "fiets"],
                ["hulajnoga", "step"],
                ["autobus", "bus"],
                ["pociąg", "trein"],
                ["samolot", "vliegtuig"],
                ["mototaxi z przyczepką", "brommerkarretje"],
                ["powóz konny", "paardewagen"],
                ["minibusy publiczne", "minibusjes"],
                ["taksówka", "taxi"],
                ["skuter", "scooter"],
                ["ciężarówka", "vrachtwagen"],
                ["karetka", "ambulance"],
                ["wóz strażacki", "brandweerauto"],
                ["radiowóz policyjny", "politieauto"]
            ],
            "trasa": [
                ["trasy", "route"],
                ["trasa", "route"],
                ["droga", "weg"],
                ["autostrada", "snelweg"],
                ["zjazd", "afslag"],
                ["kierunek", "richting"],
                ["w prawo", "rechtsaf"],
                ["w lewo", "linksaf"],
                ["prosto", "rechtdoor"],
                ["objazd", "omleiding"],
                ["nawigacja", "navigatie"],
                ["mapa", "kaart"],
                ["GPS", "gps"]
            ],
            "przepisy": [
                ["przepisy ruchu drogowego", "regels"],
                ["przepisy drogowe", "verkeersregels"],
                ["ograniczenie prędkości", "snelheidslimiet"],
                ["sygnalizacja świetlna", "stoplicht"],
                ["pierwszeństwo", "voorrang"],
                ["zakaz wyprzedzania", "inhaalverbod"],
                ["pas bezpieczeństwa", "riem"],
                ["kask", "helm"],
                ["mandat / kara", "boete"],
                ["prawo jazdy", "rijbewijs"],
                ["zakaz parkowania", "parkeerverbod"],
                ["obowiązkowa ścieżka rowerowa", "fietspad verplicht"],
                ["jazda po prawej stronie", "rechts rijden"]
            ],
            "zakupy": [
                ["zakupy", "winkelen"],
                ["robić zakupy / shopping", "shoppen"],
                ["kupować ubrania", "kleren kopen"],
                ["wyprzedaż", "uitverkoop"],
                ["centrum handlowe", "winkelcentrum"],
                ["przymierzalnia", "pashokje"],
                ["kasa", "kassa"],
                ["paragon / bilet", "bonnetje"],
                ["zwrot", "retour"],
                ["rozmiar", "grootte"],
                ["zniżka", "korting"],
                ["wózek sklepowy", "winkelwagen"],
                ["płacić", "betalen"]
            ],
            "centrum_handlowe": [
                ["centrum handlowe", "mall"],
                ["centrum handlowe / mall", "winkelcentrum"],
                ["kino", "bioscoop"],
                ["stoisko z jedzeniem / food court", "foodcourt"],
                ["winda / schody ruchome", "lift"],
                ["parkować", "parkeren"],
                ["toaleta", "toilet"],
                ["atrium", "atrium"],
                ["fontanna", "fontein"],
                ["plac zabaw dla dzieci", "speelplaats"],
                ["bilet do kina", "bioscoopticket"],
                ["promocja", "promotie"],
                ["obsługa klienta", "klantenservice"]
            ],
            "sklepik": [
                ["sklepy", "toko"],
                ["sklep", "winkel"],
                ["sklep spożywczy / spożywczak", "kruidenier"],
                ["targ / rynek", "markt"],
                ["supermarket", "supermarkt"],
                ["sklep osiedlowy / minimarket", "minimarkt"],
                ["kasa", "kassa"],
                ["cena", "prijs"],
                ["paragon / faktura", "rekening"],
                ["torba foliowa", "plastic zak"],
                ["świeży", "vers"],
                ["pakunek", "pakket"],
                ["płacić przy kasie", "afrekenen"]
            ],
            "warung": [
                ["stragany z jedzeniem", "warung"],
                ["stragan z jedzeniem / warung", "eetstalletje"],
                ["kawa", "koffie"],
                ["herbata", "thee"],
                ["smażony ryż", "nasi goreng"],
                ["smażone makaron", "mie goreng"],
                ["satay / szaszłyki", "saté"],
                ["zupa", "soep"],
                ["lody", "ijs"],
                ["papieros", "sigaret"],
                ["plastikowe krzesło", "plastic stoel"],
                ["na wynos", "take away"],
                ["rachunek", "rekening"]
            ],
            "restaurant": [
                ["restauracja", "restaurant"],
                ["menu", "menu"],
                ["kelner", "ober"],
                ["zamawiać", "bestellen"],
                ["rachunek", "rekening"],
                ["napiwek", "fooi"],
                ["przystawka / przystawka", "voorgerecht"],
                ["danie główne", "hoofdgerecht"],
                ["deser", "nagerecht"],
                ["napój", "drinken"],
                ["rezerwować", "reserveren"],
                ["stół", "tafel"]
            ],
    "klubowanie": [
                ["klubowanie", "clubbing"],
                ["dyskoteka / klub nocny", "discotheek"],
                ["parkiet taneczny", "dansvloer"],
                ["DJ", "dj"],
                ["muzyka", "muziek"],
                ["drink / napój", "drankje"],
                ["impreza / party", "feest"],
                ["ochroniarz / bramkarz", "bouncer"],
                ["opłata za wejście", "cover charge"],
                ["show świetlny", "lightshow"],
                ["after / impreza po imprezie", "afterparty"],
                ["tłum", "crowd"],
                ["chill / na luzie", "chill"]
            ],
            "koncert": [
                ["koncert", "concert"],
                ["bilety", "kaartje"],
                ["bilet / wejściówka", "kaartje"],
                ["scena", "podium"],
                ["zespół / grupa", "band"],
                ["wokalista / piosenkarz", "zanger"],
                ["gitara", "gitaar"],
                ["perkusja", "drum"],
                ["publiczność", "publiek"],
                ["oklaski", "applaus"],
                ["bis / encore", "encore"],
                ["festiwal", "festival"],
                ["dźwięk", "geluid"]
            ],
            "knajpa": [
                ["knajpa / pub", "kroeg"],
                ["piwo", "biertje"],
                ["piwo pils", "pils"],
                ["jałowcówka / jenever", "jenever"],
                ["kieliszek / coś na ząb", "borrel"],
                ["barman", "barkeeper"],
                ["stołek barowy", "kruk"],
                ["przekąska / tapas", "hapje"],
                ["bilard", "biljart"],
                ["rzutki", "darts"],
                ["muzyka w tle", "muziekje"],
                ["późno / w nocy", "laat"]
            ],
            "słuchanie": [
                ["słuchanie", "luisteren"],
                ["słuchać", "luisteren"],
                ["słuchać muzyki", "muziek luisteren"],
                ["playlista", "playlist"],
                ["słuchawki", "koptelefoon"],
                ["słuchawki douszne / earbudsy", "oortjes"],
                ["głośność", "volume"],
                ["utwór / piosenka", "nummer"],
                ["album", "album"],
                ["artysta", "artiest"],
                ["streaming", "streaming"],
                ["pobrać / ściągnąć", "downloaden"],
                ["odtwarzać", "afspelen"]
            ],
            "instrumenty": [
                ["instrumenty", "instrumenten"],
                ["gitara", "gitaar"],
                ["fortepian / piano", "piano"],
                ["perkusja / bębny", "drum"],
                ["skrzypce", "viool"],
                ["gitara basowa", "basgitaar"],
                ["flet", "fluit"],
                ["trąbka", "trompet"],
                ["saksofon", "saxfoon"],
                ["klawiatura", "keyboard"],
                ["ukulele", "ukulele"],
                ["harmonijka", "harmonica"],
                ["wiolonczela", "cello"]
            ],
            "audio": [
                ["audio", "audio"],
                ["dźwięk", "geluid"],
                ["głośnik", "luidspreker"],
                ["mikrofon", "microfoon"],
                ["jakość dźwięku", "geluidskwaliteit"],
                ["stereo", "stereo"],
                ["surround", "surround"],
                ["mp3", "mp3"],
                ["wav", "wav"],
                ["bitrate", "bitrate"],
                ["wzmacniacz", "versterker"],
                ["rejestrator", "recorder"],
                ["podcast", "podcast"]
            ],
            "hifi": [
                ["hi-fi", "hifi"],
                ["hi-fi", "hifi"],
                ["wzmacniacz", "versterker"],
                ["głośnik hi-fi", "luidspreker"],
                ["gramofon / odtwarzacz płyt winylowych", "platenspeler"],
                ["odtwarzacz CD", "cd-speler"],
                ["DAC", "dac"],
                ["analogowy", "analoog"],
                ["cyfrowy", "digitaal"],
                ["winyl", "vinyl"],
                ["lampa / lampa próżniowa", "tube"],
                ["tuner", "tuner"],
                ["odbiornik / receiver", "receiver"]
            ],
            "nieformalny": [
                ["nieformalny", "informeel"],
                ["yo / ziom", "yo"],
                ["hej / hejka", "hé"],
                ["fajny / super", "gaaf"],
                ["luz / na luzie", "chill"],
                ["pyszny / super", "lekker"],
                ["Cieszę się atmosferą, mega fajnie!", "Ik geniet even van de gezelligheid, super leuk!"],
                ["zajebisty / mega", "vet"],
                ["spoko / nic się nie dzieje", "niks aan de hand"],
                ["pa / nara", "doei"],
                ["do zaraz", "tot zo"],
                ["później", "later"],
                ["okej / spoko", "oké"],
                ["jasne / pewnie", "tuurlijk"]
            ],
            "formalny": [
                ["formalny", "formeel"],
                ["dzień dobry", "goedemorgen"],
                ["dobry dzień / dobre popołudnie", "goedemiddag"],
                ["dobry wieczór", "goedenavond"],
                ["bardzo dziękuję", "dank u wel"],
                ["proszę", "alstublieft"],
                ["przepraszam", "excuseer mij"],
                ["z kim rozmawiam?", "met wie spreek ik?"],
                ["mówi", "u spreekt met"],
                ["do widzenia", "tot ziens"],
                ["miłego dnia", "prettige dag"],
                ["nie ma za co", "graag gedaan"],
                ["Bardzo miło cieszyć się ciepłem bycia razem z rodziną i przyjaciółmi", "Heel fijn om van de warmte van samen zijn met familie en vrienden te genieten"],
                ["czy mogę pana/panią o coś zapytać?", "mag ik u iets vragen?"]
            ],
            "przyjaciele": [
                ["przyjaciele", "vrienden"],
                ["przyjaciel", "vriend"],
                ["najlepszy przyjaciel", "beste vriend"],
                ["kumpel / towarzysz", "kameraad"],
                ["dziś wieczorem spotykamy się z kumplami", "vanavond bij elkaar met vrienden"],
                ["cieszyć się gadaniem do późna w nocy", "genieten van het geklets tot diep in de nacht"],
                ["kumpel / ziom", "maatje"],
                ["kumpel / buddy", "buddy"],
                ["wisieć / chillować", "hangen"],
                ["chillować / wyluzować", "chillen"],
                ["imprezka / mała impreza", "feestje"],
                ["wychodzić / imprezować", "uitgaan"],
                ["wiadomość / appka", "appje"],
                ["szybki telefon / dzwonek", "belletje"],
                ["umawiać się", "afspreken"]
            ],
            "ulica": [
                ["ulica", "straat"],
                ["chodnik", "stoep"],
                ["zebra / przejście dla pieszych", "zebrapad"],
                ["sygnalizacja świetlna", "verkeerslicht"],
                ["samochód", "auto"],
                ["rower", "fiets"],
                ["pieszy", "voetganger"],
                ["znak / tablica", "bord"],
                ["latarnia uliczna", "lantaarnpaal"],
                ["kosz na śmieci", "vuilnisbak"],
                ["tablica z nazwą ulicy", "straatnaambord"],
                ["przejście dla pieszych", "oversteekplaats"]
            ],
            "zabawki": [
                ["zabawki", "speelgoed"],
                ["lalka", "pop"],
                ["miś pluszowy / teddy", "beer"],
                ["samochodzik", "auto"],
                ["piłka", "bal"],
                ["lego", "lego"],
                ["puzzle", "puzzel"],
                ["klocki", "blok"],
                ["pociąg zabawka", "trein"],
                ["samolot zabawka", "vliegtuig"],
                ["pluszak / przytulanka", "knuffel"],
                ["domek dla lalek", "poppenhuis"],
                ["książeczka do kolorowania", "kleurboek"]
            ],
            "gry_elektroniczne": [
                ["gry elektroniczne", "e-games"],
                ["gra", "spel"],
                ["gra wideo / videojuego", "videogame"],
                ["komputer", "computer"],
                ["telefon", "telefoon"],
                ["kontroler / pad", "controller"],
                ["poziom / level", "level"],
                ["punkty", "punten"],
                ["multiplayer", "multiplayer"],
                ["online", "online"],
                ["postać / charakter", "karakter"],
                ["wygrać", "win"],
                ["przegrać", "verlies"]
            ],
            "gry_planszowe": [
                ["gry planszowe", "board-games"],
                ["gra planszowa", "bordspel"],
                ["szachy", "schaken"],
                ["warcaby", "dammen"],
                ["monopoly", "monopoly"],
                ["nie daj się", "mens erger je niet"],
                ["karty", "kaarten"],
                ["kostka do gry", "dobbelsteen"],
                ["strategia", "strategie"],
                ["tura / kolejka", "beurt"],
                ["zwycięzca", "winnaar"],
                ["gracz", "speler"],
                ["plansza", "bord"]
            ],
    "sauna": [
                ["sauna", "sauna"],
                ["sauna", "sauna"],
                ["łaźnia parowa", "stoomcabine"],
                ["gorąco / ciepło", "hitte"],
                ["relaksować się", "relaxen"],
                ["pocenie się", "zweten"],
                ["ręcznik", "handdoek"],
                ["zimna kąpiel", "koud bad"],
                ["gorąca łaźnia parowa", "stoombad"],
                ["sesja saunowa", "saunagang"],
                ["pomieszczenie wypoczynkowe", "rustruimte"],
                ["napar / picie dużej ilości wody", "infuus"],
                ["czapka saunowa", "saunamuts"]
            ],
            "terapia": [
                ["terapie", "therapie"],
                ["terapia", "therapie"],
                ["masaż", "massage"],
                ["aromaterapia", "aromatherapie"],
                ["joga", "yoga"],
                ["medytacja", "meditatie"],
                ["refleksologia", "reflexologie"],
                ["akupunktura", "acupunctuur"],
                ["reiki", "reiki"],
                ["relaksacja", "ontspanning"],
                ["stres", "stress"],
                ["oddychanie", "ademhaling"],
                ["mindfulness / uważność", "mindfulness"]
            ],
            "w_domu": [
                ["w domu", "thuis"],
                ["w domu", "thuis"],
                ["relaksować się", "relaxen"],
                ["kanapa / sofa", "bank"],
                ["cieszyć się (formalnie)", "genieten van (formeel)"],
                ["cieszyć się / delektować się (nieformalnie)", "genieten van (informeel)"],
                ["herbata", "thee"],
                ["być razem", "samen zijn"],
                ["mieszkać razem", "samenwonen"],
                ["książka", "boek"],
                ["muzyka", "muziek"],
                ["świeca", "kaars"],
                ["kąpiel", "bad"],
                ["oglądać film", "film kijken"],
                ["spać", "slapen"],
                ["spokojny", "rustig"],
                ["wygodny", "comfortabel"]
            ],
            "z_rodziną": [
                ["z rodziną", "met_familie"],
                ["rodzina", "familie"],
                ["razem", "samen"],
                ["gra / gierka", "spelletje"],
                ["wieczór filmowy", "filmavond"],
                ["jeść razem", "eten"],
                ["radość", "vreugde"],
                ["szczęście", "geluk"],
                ["miłość", "liefde"],
                ["trudności / przeciwności", "tegenspoed"],
                ["smutek", "verdriet"],
                ["rozmawiać", "praten"],
                ["w czasach", "in tijden van"],
                ["razem w dobrych i złych czasach", "samen in voor en tegenspoed"],
                ["przytulać się / przytulanie", "knuffelen"],
                ["wycieczka / wyjście rodzinne", "uitstapje"],
                ["wspomnienie", "herinnering"],
                ["śmiać się", "lachen"],
                ["spokojnie razem", "rustig"],
                ["w domu razem", "thuis"]
            ],

    "wnętrze": [
                ["dashboard", "tablero / salpicadero"],
                ["stuurwiel", "volante"],
                ["stoel", "asiento"],
                ["bank", "asiento trasero / banqueta trasera"],
                ["veiligheidsgordel", "cinturón de seguridad"],
                ["airbag", "airbag / bolsa de aire"],
                ["handschoenenvak", "guantera / compartimento del tablero"],
                ["pook", "palanca de cambios / palanca de velocidades"],
                ["pedalen", "pedales"],
                ["raam", "ventana"],
                ["spiegel", "espejo retrovisor"],
                ["zonneklep", "parasol / visera solar"]
            ],
            "części": [
                ["motor", "motor"],
                ["accu", "batería / acumulador"],
                ["rem", "freno"],
                ["band", "neumático / llanta"],
                ["velg", "llanta / rin"],
                ["uitlaat", "escape / tubo de escape"],
                ["radiator", "radiador"],
                ["olie", "aceite"],
                ["filter", "filtro"],
                ["bougie", "bujía"],
                ["distributieriem", "correa de distribución / correa de tiempo"],
                ["schokdemper", "amortiguador"]
            ],
            "metale": [
                ["ijzer", "hierro"],
                ["staal", "acero"],
                ["aluminium", "aluminio"],
                ["koper", "cobre"],
                ["lood", "plomo"],
                ["zink", "zinc"],
                ["tin", "estaño"],
                ["nikkel", "níquel"],
                ["chroom", "cromo"],
                ["magnesium", "magnesio"],
                ["titanium", "titanio"],
                ["goud", "oro"],
                ["zilver", "plata"],
                ["brons", "bronce"],
                ["puur goud", "oro puro"]
            ],
            "surfing": [
                ["surfing", "surfing"],
                ["surfować", "surfen"],
                ["deska surfingowa", "surfplank"],
                ["fale", "golven"],
                ["duża fala / big wave", "big wave"],
                ["shortboard", "shortboard"],
                ["longboard", "longboard"],
                ["smycz / leash", "leash"],
                ["wosk do deski", "wax"],
                ["miejsce do surfowania / surfspot", "surfspot"],
                ["wpaść na falę / drop in", "drop in"],
                ["wywrotka / wipeout", "wipeout"],
                ["miejsce / spot", "spot"],
                ["deska", "board"],
                ["fala", "golf"],
                ["morze", "zee"],
                ["plaża", "strand"],
                ["rura / barrel", "barrel"],
                ["ziom / koleś", "dude"]
            ],

    "piłka_nożna": [
                ["piłka nożna", "voetbal"],
                ["trawa / murawa", "gras"],
                ["mecz", "wedstrijd"],
                ["bramka", "doel"],
                ["gracz / piłkarz", "speler"],
                ["bramkarz", "doelman"],
                ["sędzia", "scheidsrechter"],
                ["gol", "goal"],
                ["rzut karny / penalty", "penalty"],
                ["rzut wolny", "vrije trap"],
                ["róg / korner", "corner"],
                ["kartka", "kaart"],
                ["gwizdek", "fluiten"]
            ],
            "elegancko": [
                ["elegancki / formalny", "netjes"],
                ["garnitur / marynarka i spodnie", "pak"],
                ["krawat", "stropdas"],
                ["koszula", "overhemd"],
                ["marynarka / blazer", "blazer"],
                ["spódnica", "rok"],
                ["sukienka", "jurk"],
                ["szpilki / buty na obcasie", "pumps"],
                ["garnitur kompletny", "kostuum"],
                ["kamizelka", "vest"],
                ["krawat", "das"],
                ["spinki do mankietów", "manchetknopen"],
                ["pasek", "riem"]
            ],
            "zwykły": [
                ["zwykły / codzienny", "gewoon"],
                ["dżinsy / jeansy", "spijkerbroek"],
                ["koszulka / T-shirt", "T-shirt"],
                ["sweter / pulower", "trui"],
                ["bluza z kapturem", "hoodie"],
                ["adidasy / sneakersy", "sneaker"],
                ["szorty / krótkie spodenki", "short"],
                ["koszula casual", "shirt"],
                ["sukienka casual", "jurk"],
                ["legginsy", "legging"],
                ["dres / spodnie dresowe", "joggingbroek"],
                ["top / bluzka", "top"],
                ["lekka kurtka / kardigan", "vest"]
            ],
            "wystrojony": [
                ["odstawiony / wystrojony", "opgedirkt"],
                ["szpilki / wysokie obcasy", "high heels"],
                ["sukienka koktajlowa", "cocktailjurk"],
                ["smoking", "smoking"],
                ["krawat", "stropdas"],
                ["makijaż", "make-up"],
                ["biżuteria / klejnoty", "juwelen"],
                ["eleganckie ubrania / luksusowa odzież", "kleding"],
                ["stroje wieczorowe / strój galowy", "avondkleding"],
                ["błysk / cekiny", "glitter"],
                ["perły / koraliki", "kralen"],
                ["szpilki typu stiletto", "stiletto"],
                ["kopertówka / mała torebka wieczorowa", "clutch"]
            ],
            "buty": [
                ["buty", "schoenen"],
                ["adidasy / buty sportowe", "sneaker"],
                ["buty / kozaki", "laarzen"],
                ["sandały", "sandalen"],
                ["obcasy", "hakken"],
                ["chodaki / drewniaki", "klompen"],
                ["klapki / japonki", "slippers"],
                ["szpilki / buty na obcasie", "pumps"],
                ["buty sportowe", "sportschoenen"],
                ["mokasyny / loafersy", "loafers"],
                ["sneakersy / trampki", "sneakers"],
                ["pudełko na buty", "schoenendoos"]
            ],
            "1_do_10": [
                ["liczby od 1 do 10", "1_tot_10"],
                ["jeden", "één"],
                ["dwa", "twee"],
                ["trzy", "drie"],
                ["cztery", "vier"],
                ["pięć", "vijf"],
                ["sześć", "zes"],
                ["siedem", "zeven"],
                ["osiem", "acht"],
                ["dziewięć", "negen"],
                ["dziesięć", "tien"],
                ["zero", "nul"],
                ["plus", "plus"]
            ],
            "duże_liczby": [
                ["duże liczby", "grote_cijfers"],
                ["sto", "honderd"],
                ["tysiąc", "duizend"],
                ["dziesięć tysięcy", "tienduizend"],
                ["sto tysięcy", "honderdduizend"],
                ["milion", "miljoen"],
                ["dziesięć milionów", "tien miljoen"],
                ["sto milionów", "honderd miljoen"],
                ["miliard", "miljard"],
                ["bilion", "biljoen"],
                ["pierwszy", "eerste"],
                ["drugi", "tweede"],
                ["trzeci", "derde"]
            ],
            "matematyka": [
                ["matematyka", "wiskunde"],
                ["plus", "plus"],
                ["minus", "min"],
                ["razy / pomnożone przez", "keer"],
                ["dzielone przez", "delen"],
                ["równa się", "gelijk"],
                ["suma", "som"],
                ["różnica", "verschil"],
                ["iloczyn", "product"],
                ["iloraz", "quotiënt"],
                ["ułamek", "breuk"],
                ["procent", "procent"],
                ["kwadrat", "vierkant"]
            ],
            "telewizja": [
                ["telewizja", "tv"],
                ["telewizja", "televisie"],
                ["TV", "tv"],
                ["program", "programma"],
                ["kanał", "zender"],
                ["pilot", "afstandsbediening"],
                ["kanał telewizyjny", "kanaal"],
                ["seria / serial", "series"],
                ["wiadomości", "nieuws"],
                ["film", "film"],
                ["program reality / reality show", "realityshow"],
                ["reklama", "reclame"],
                ["smart TV / inteligentna telewizja", "smart TV"]
            ],
            "filmy": [
                ["filmy", "movies"],
                ["film", "film"],
                ["kino", "bioscoop"],
                ["film akcji", "actiefilm"],
                ["komedia", "komedie"],
                ["dramat", "drama"],
                ["horror / straszny film", "horror"],
                ["thriller / film suspense", "thriller"],
                ["animacja", "animatie"],
                ["dokument", "documentaire"],
                ["zwiastun / trailer", "trailer"],
                ["aktor", "acteur"],
                ["reżyser", "regisseur"]
            ],
            "rodzaje": [
                ["pogoda", "soorten"],
                ["pogoda / klimat", "weer"],
                ["słoneczny", "zonnig"],
                ["pochmurny", "bewolkt"],
                ["deszcz", "regen"],
                ["burza / grzmot", "onweer"],
                ["mgła", "mist"],
                ["wiatr", "wind"],
                ["śnieg", "sneeuw"],
                ["grad", "hagel"],
                ["burza / sztorm", "storm"],
                ["ciepło / gorąco", "warm"],
                ["zimno", "koud"]
            ],
            "klimat": [
                ["klimat", "klimaat"],
                ["klimat", "klimaat"],
                ["tropikalny", "tropisch"],
                ["śródziemnomorski", "mediterraan"],
                ["kontynentalny", "continentaal"],
                ["polarny", "polair"],
                ["pustynia", "woestijn"],
                ["las deszczowy / tropikalny deszczowy las", "regenwoud"],
                ["średnia temperatura", "gemiddelde temperatuur"],
                ["opady", "neerslag"],
                ["pora roku / sezon", "seizoen"],
                ["suchy", "droog"],
                ["wilgotny", "vochtig"]
            ],
            "praca": [
                ["praca", "baan"],
                ["praca / zatrudnienie", "baan"],
                ["praca", "werk"],
                ["aplikacja o pracę / podanie o pracę", "sollicitatie"],
                ["CV / życiorys", "cv"],
                ["pensja / wynagrodzenie", "salaris"],
                ["umowa", "contract"],
                ["wakacje / urlop", "vakantie"],
                ["nadgodziny", "overwerk"],
                ["kolega z pracy", "collega"],
                ["szef", "baas"],
                ["zwolnienie / wypowiedzenie", "ontslag"],
                ["emerytura", "pensioen"]
            ],
            "drewno": [
                ["drewno", "hout"],
                ["piła", "zaag"],
                ["młot / młotek", "hamer"],
                ["gwóźdź", "spijker"],
                ["śruba / wkręt", "schroef"],
                ["wiertarka", "boor"],
                ["papier ścierny / szmergiel", "schuurpapier"],
                ["klej", "lijm"],
                ["farba", "verf"],
                ["dłuto", "beitel"],
                ["miarka / taśma miernicza", "meetlint"],
                ["ławka warsztatowa / stół roboczy", "werkbank"]
            ],
            "w_pomieszczeniu": [
                ["indoor / w pomieszczeniach", "indoor"],
                ["śrubokręt", "schroevendraaier"],
                ["szczypce / kombinerki", "tang"],
                ["klucz francuski / klucz płaski", "moersleutel"],
                ["klucz imbusowy / klucz sześciokątny", "inbussleutel"],
                ["wtyczka", "plug"],
                ["lampa", "lamp"],
                ["gniazdo / gniazdko elektryczne", "stopcontact"],
                ["wałek malarski", "verfroller"],
                ["pędzel", "kwast"],
                ["miarka / taśma miernicza", "meetlint"],
                ["poziomica / poziomica z bąbelkiem", "waterpas"],
                ["odkurzacz", "stofzuiger"]
            ],
            "na_zewnątrz": [
                ["outdoor / na zewnątrz", "outdoor"],
                ["kosiarka do trawy", "grasmaaier"],
                ["grabie", "hark"],
                ["łopata", "schep"],
                ["wąż ogrodowy", "tuinslang"],
                ["piła", "zaag"],
                ["młot / młotek", "hamer"],
                ["szpadel / duża łopata", "spade"],
                ["taczka", "kruiwagen"],
                ["sekator", "snoeischaar"],
                ["szczotka ogrodowa", "tuinborstel"],
                ["ławka ogrodowa", "tuinbank"],
                ["mała łopatka", "schop"]
            ],
            "ciężki_sprzęt": [
                ["ciężki sprzęt", "heavy_equipment"],
                ["koparka", "graafmachine"],
                ["spycharka / buldożer", "bulldozer"],
                ["dźwig / żuraw", "kraan"],
                ["ciągnik", "tractor"],
                ["ciężarówka", "vrachtwagen"],
                ["walec / walec zagęszczający", "roller"],
                ["samochód wywrotka", "dumptruck"],
                ["ładowarka / ładowarka kołowa", "shovel"],
                ["betoniarka / mieszarka do betonu", "betonmixer"],
                ["podnośnik koszowy / podnośnik wysokościowy", "hoogwerker"],
                ["maszyna do układania asfaltu", "asfaltmachine"],
                ["wózek widłowy / forklift", "heftruck"]
            ],
            "planety": [
                ["planety", "planets"],
                ["planeta", "planeet"],
                ["słońce", "zon"],
                ["księżyc", "maan"],
                ["Merkury", "Mercurius"],
                ["Wenus", "Venus"],
                ["Ziemia", "Aarde"],
                ["Mars", "Mars"],
                ["Jowisz", "Jupiter"],
                ["Saturn", "Saturnus"],
                ["Uran", "Uranus"],
                ["Neptun", "Neptunus"],
                ["Pluton", "Pluto"]
            ],
            "gwiazdy": [
                ["gwiazdy", "stars"],
                ["gwiazda", "ster"],
                ["gwiazdozbiór / konstelacja", "sterrenbeeld"],
                ["Droga Mleczna", "Melkweg"],
                ["jasny / świetlisty", "helder"],
                ["spadająca gwiazda", "vallende ster"],
                ["nowa", "nova"],
                ["supernowa", "supernova"],
                ["czarna dziura", "zwarte gat"],
                ["konstelacja", "constellatie"],
                ["Gwiazda Polarna / Polaris", "poolster"],
                ["Syriusz", "Sirius"],
                ["Orion", "Orion"]
            ],
            "zodiak": [
                ["zodiak", "zodiac"],
                ["Baran", "Ram"],
                ["Byk", "Stier"],
                ["Bliźnięta", "Tweelingen"],
                ["Rak", "Kreeft"],
                ["Lew", "Leeuw"],
                ["Panna", "Maagd"],
                ["Waga", "Weegschaal"],
                ["Skorpion", "Schorpioen"],
                ["Strzelec", "Boogschutter"],
                ["Koziorożec", "Steenbok"],
                ["Wodnik", "Waterman"],
                ["Ryby", "Vissen"]
            ],
            "urzędnicy": [
                ["urzędnicy / funkcjonariusze publiczni", "officials"],
                ["prezydent", "president"],
                ["minister", "minister"],
                ["parlament", "parlement"],
                ["premier / premier rządu", "premier"],
                ["burmistrz", "burgemeester"],
                ["gubernator", "gouverneur"],
                ["urzędnik państwowy", "ambtenaar"],
                ["dyplomata", "diplomaat"],
                ["sędzia", "rechter"],
                ["szef policji", "politiechef"],
                ["senator", "senator"],
                ["poseł / członek parlamentu", "parlementslid"]
            ],
            "ratusz": [
                ["ratusz", "stadhuis"],
                ["ratusz / urząd miejski", "stadhuis"],
                ["gmina / urząd miasta", "gemeente"],
                ["burmistrz", "burgemeester"],
                ["sala posiedzeń rady", "raadszaal"],
                ["urząd stanu cywilnego / rejestr mieszkańców", "burgerzaken"],
                ["sala ślubów cywilnych", "trouwzaal"],
                ["pozwolenie / licencja", "vergunning"],
                ["podatki miejskie", "belasting"],
                ["paszport", "paspoort"],
                ["dowód osobisty", "identiteitskaart"],
                ["archiwum", "archief"],
                ["okienko / punkt obsługi", "loket"]
            ],
            "komisariat_policji": [
                ["komenda policji", "politieburo"],
                ["komenda policji", "politiebureau"],
                ["policjant", "politieagent"],
                ["komisarz", "commissaris"],
                ["zawiadomienie / zgłoszenie", "aangifte"],
                ["przesłuchanie", "verhoor"],
                ["kajdanki", "handboeien"],
                ["patrol", "patrouille"],
                ["aresztowanie / zatrzymanie", "arrestatie"],
                ["protokół policyjny", "proces-verbaal"],
                ["świadek", "getuige"],
                ["podejrzany", "verdachte"],
                ["ofiara", "slachtoffer"]
            ],

    "kościół": [
                ["kościół", "kerk"],
                ["kościół", "kerk"],
                ["ksiądz / pastor", "priester"],
                ["msza", "mis"],
                ["kazanie", "preek"],
                ["ołtarz", "altaar"],
                ["krzyż", "kruis"],
                ["Biblia", "bijbel"],
                ["chrzest", "doop"],
                ["ślub kościelny", "huwelijk"],
                ["pogrzeb / ceremonia pogrzebowa w kościele", "begrafenis"],
                ["chór", "koor"],
                ["dzwon kościelny", "klok"]
            ],
            "islam": [
                ["islam", "islam"],
                ["meczet", "moskee"],
                ["modlitwa / salat", "gebed"],
                ["ramadan", "ramadan"],
                ["post", "vasten"],
                ["Koran", "koran"],
                ["prorok", "profeet"],
                ["Mekka", "mecca"],
                ["hadżdż / pielgrzymka do Mekki", "hadj"],
                ["imam", "imam"],
                ["azan / wezwanie do modlitwy", "azaan"],
                ["modlitwa piątkowa", "vrijdaggebed"],
                ["zakat / obowiązkowa jałmużna", "zakat"]
            ],
            "protestantyzm": [
                ["protestantyzm", "protestantism"],
                ["protestancki", "protestants"],
                ["kościół", "kerk"],
                ["pastor / kaznodzieja protestancki", "predikant"],
                ["Biblia", "bijbel"],
                ["kazanie", "preek"],
                ["chrzest", "dopen"],
                ["Wieczerza Pańska / komunia", "avondmaal"],
                ["psalm", "psalm"],
                ["szkoła niedzielna", "zondagsschool"],
                ["reformacja", "hervorming"],
                ["kalwinizm", "calvinisme"],
                ["luteryzm", "lutheranisme"]
            ],
            "katolicyzm": [
                ["katolicyzm", "catholicism"],
                ["katolicki", "katholiek"],
                ["papież", "paus"],
                ["msza", "mis"],
                ["ksiądz", "priester"],
                ["spowiedź", "biecht"],
                ["komunia", "communie"],
                ["chrzest", "doop"],
                ["święty / święta", "heilige"],
                ["krzyż", "kruis"],
                ["różańiec", "rozenkrans"],
                ["klasztor / klasztor", "klooster"],
                ["katedra", "kathedraal"]
            ],
            "hinduizm": [
                ["hinduizm", "hinduism"],
                ["hindus", "hindoe"],
                ["dharma", "dharma"],
                ["karma", "karma"],
                ["reinkarnacja", "reïncarnatie"],
                ["świątynia", "tempel"],
                ["bóg", "god"],
                ["bogini", "goddess"],
                ["Ganeśa", "ganesha"],
                ["Śiwa", "shiva"],
                ["Wisznu", "vishnu"],
                ["Brahma", "brahma"],
                ["puja / czczenie", "puja"]
            ],
            "buddyzm": [
                ["buddyzm", "buddhism"],
                ["buddyzm", "boeddhisme"],
                ["Budda", "boeddha"],
                ["dharma", "dharma"],
                ["nirwana", "nirvana"],
                ["medytacja", "meditatie"],
                ["świątynia", "tempel"],
                ["mnich", "monnik"],
                ["mniszka", "non"],
                ["karma", "karma"],
                ["cztery szlachetne prawdy", "vier edele waarheden"],
                ["szlachetna ośmioraka ścieżka", "achtvoudig pad"],
                ["posąg Buddy", "boeddha-beeld"]
            ],
            "konfucjanizm": [
                ["konfucjanizm", "confucianism"],
                ["konfucjanizm", "confucianisme"],
                ["Konfucjusz", "Confucius"],
                ["filozofia", "filosofie"],
                ["harmonia", "harmonie"],
                ["szacunek", "respect"],
                ["rodzina", "familie"],
                ["obowiązek", "plicht"],
                ["mądrość", "wijsheid"],
                ["rytuał / ceremonia", "ritueel"],
                ["nauczyciel", "leraar"],
                ["moralność", "moreel"],
                ["cnota", "deugd"]
            ],
            "komputer": [
                ["komputer", "pc"],
                ["komputer", "computer"],
                ["laptop", "laptop"],
                ["komputer stacjonarny", "desktop"],
                ["klawiatura", "toetsenbord"],
                ["mysz", "muis"],
                ["ekran / monitor", "scherm"],
                ["procesor", "processor"],
                ["pamięć / RAM", "geheugen"],
                ["dysk twardy", "harde schijf"],
                ["system operacyjny", "besturingssysteem"],
                ["internet", "internet"],
                ["oprogramowanie", "software"]
            ],
            "audio": [
                ["audio", "audio"],
                ["dźwięk", "geluid"],
                ["głośnik", "luidspreker"],
                ["słuchawki z mikrofonem / headset", "headset"],
                ["mikrofon", "microfoon"],
                ["słuchawki", "hoofdtelefoon"],
                ["wzmacniacz", "versterker"],
                ["subwoofer", "subwoofer"],
                ["soundbar", "soundbar"],
                ["mp3", "mp3"],
                ["streaming", "streaming"],
                ["podcast", "podcast"],
                ["karta dźwiękowa", "geluidskaart"]
            ],
            "wideo": [
                ["wideo", "video"],
                ["wideo", "video"],
                ["kamera", "camera"],
                ["film", "film"],
                ["streaming", "streaming"],
                ["YouTube", "YouTube"],
                ["Netflix", "Netflix"],
                ["rozdzielczość", "resolutie"],
                ["4K", "4K"],
                ["HD", "HD"],
                ["edytować", "editen"],
                ["wgrać / przesłać", "uploaden"],
                ["pobrać", "downloaden"]
            ],
            "żeglowanie": [
                ["żeglowanie", "zeilen"],
                ["żeglować / żeglowanie", "zeilen"],
                ["jacht żaglowy / łódź żaglowa", "zeilboot"],
                ["żagiel", "zeil"],
                ["maszt", "mast"],
                ["szkota / lina żaglowa", "schoot"],
                ["wiatr", "wind"],
                ["kurs", "koers"],
                ["port / przystań", "haven"],
                ["kotwiczyć", "ankeren"],
                ["kil", "kiel"],
                ["spinnaker", "spinnaker"],
                ["jacht", "jacht"]
            ],
            "łódź": [
                ["łodzie", "boot"],
                ["łódź", "boot"],
                ["łódź wiosłowa", "roeiboot"],
                ["łódź motorowa szybka / speedboat", "speedboot"],
                ["łódź motorowa", "motorboot"],
                ["kanoe", "kano"],
                ["kajak", "kajak"],
                ["ster", "roer"],
                ["pokład", "dek"],
                ["kabina", "cabine"],
                ["kotwica", "anker"],
                ["kamizelka ratunkowa", "reddingsvest"],
                ["paliwo", "brandstof"]
            ],
            "morze_ocean": [
                ["morze i ocean", "zee_oceaan"],
                ["morze", "zee"],
                ["ocean", "oceaan"],
                ["plaża", "strand"],
                ["fala", "golf"],
                ["przypływ i odpływ / pływ", "getijde"],
                ["prąd morski", "stroming"],
                ["nurkowac", "duiken"],
                ["pływać", "zwemmen"],
                ["łowić ryby", "vissen"],
                ["muszelka / muszla", "schelp"],
                ["woda słona", "zout water"],
                ["koral", "koraal"]
            ],

            }
    };