const sharedData = { 


  groupz: {
    "Basics": "makkelijk",
    "Taal & Communicatie": "taal cijfers geld ",
    "Mens & Gezondheid": "leven baan_werk medisch",
    "Eten & Drinken": "eten ingredienten boodschappen",
    "Natuur & Milieu": "natuur weer steen metalen",
    "Vrije Tijd & Lifestyle": "uitgaan sport hobby kleding muziek tec",
    "Reizen & Vervoer": "reizen verkeer auto space",
    "Huis & Wonen": "relaxen gereedschap",
    "Cultuur & Samenleving": "religie politiek officieel_instituut"
  },
  categories: {
            "makkelijk": "1_tot_10 kleuren dieren fruit groet smaken",
            "cijfers": "1_tot_10 grote_cijfers wiskunde",
            "leven": "mensen familie familieleden straat",
            "natuur": "dieren vogels vissen bomen planten zee_creaturen insecten",
            "ingredienten": "groente fruit kruiden specerijen",
            "eten": "smaken keuken dinner ontbijt toetjes snoep",
            "boodschappen": "winkelen mall toko warung",
            "sport": "surf voetbal zeilen boot zee_oceaan",
            "weer": "soorten klimaat",
            "relaxen": "thuis met_familie sauna therapie",
            "taal": "groet omgang formeel informeel vrienden voorzetsels werkwoorden",
            "kleding": "netjes gewoon opgedirkt schoenen",
            "uitgaan": " restaurant clubbing concert kroeg",
            "medisch": "personen gebouw symptomen klachten lichaamsdelen medicijnen",
            "reizen": "vliegveld ov station",
            "verkeer": "straat fiets autos voetganger vvmiddel route regels",
            "geld": "betaal_pin betaal_cash rekening crypto",
            "hobby": "speelgoed e-games board-games kleuren",
            "muziek": "luisteren instrumenten",
            "auto": "interieur onderdelen",
            "baan_werk": "baan",
            "gereedschap": "hout indoor outdoor heavy_equipment",
            "space": "planets stars zodiac",
            "metalen": "metalen",
            "steen": "stenen edelstenen",
            "politiek": "officials",
            "officieel_instituut": "stadhuis politieburo kerk",
            "religie": "islam protestantism catholicism hinduism buddhism confucianism",
            "tec": "pc video audio hifi tv movies"
        },

   wordLists: {
            "mensen": [
                ["ik", "yo"],
                ["jij", "tú/vos"],
                ["hij", "él"],
                ["zij (meisje)", "ella"],
                ["wij(zonder jou)", "nosotros (sin ti)"],
                ["wij(met jou)", "nosotros (contigo)"],
                ["jullie", "ustedes/vosotros"],
                ["zij (groep)", "ellos/ellas"],
                ["vriend", "amigo"],
                ["familie", "familia"],
                ["moeder", "madre"],
                ["vader", "padre"],
                ["U", "usted"]
            ],

            "familie": [
    ["opa", "abuelo / abuelo"],
    ["oma", "abuela / abuela"],
    ["vader", "padre / papá"],
    ["moeder", "madre / mamá"],
    ["broer", "hermano mayor / hermano menor"],
    ["zus", "hermana mayor / hermana menor"],
    ["zoon", "hijo / hijo varón"],
    ["dochter", "hija / hija mujer"],
    ["oom", "tío / tío"],
    ["kind", "hijo / niño"],
    ["tante", "tía / tía"],
    ["neef", "primo / sobrino varón"],
    ["nicht", "prima / sobrina mujer"]
],
"familieleden": [
    ["grootvader", "abuelo / abuelo paterno"],
    ["grootmoeder", "abuela / abuela materna"],
    ["kleinzoon", "nieto varón"],
    ["kleindochter", "nieta mujer"],
    ["schoonvader", "suegro / padre político"],
    ["schoonmoeder", "suegra / madre política"],
    ["zwager", "cuñado / hermano político varón"],
    ["schoonzus", "cuñada / hermana política mujer"],
    ["schoonbroer", "cuñado (esposo de hermana / hermano del esposo)"],
    ["schoonzus", "cuñada (esposa de hermano / hermana de la esposa)"],
    ["achteroom", "tío abuelo / tío bisabuelo"],
    ["achternicht", "prima lejana / sobrina lejana mujer"],
    ["neefje", "sobrino pequeño varón"],
    ["nichtje", "sobrina pequeña mujer"],
    ["schoonfamilie", "familia política / suegros"],
    ["familie", "familia"],
    ["verwant", "pariente / familiar lejano"]
],

"stenen": [
    ["steen", "piedra"],
    ["rots", "roca / coral"],
    ["kei", "piedra de río"],
    ["grind", "grava / piedrecitas"],
    ["zandsteen", "arenisca"],
    ["kalksteen", "caliza"],
    ["graniet", "granito"],
    ["marmer", "mármol / piedra de alabastro"],
    ["leisteen", "pizarra / esquisto"],
    ["basalt", "basalto"],
    ["lava", "lava / lahar"],
    ["puimsteen", "piedra pómez"],
    ["klei", "arcilla"],
    ["kristal", "cristal"],
    ["erts", "mineral / mena"]
],
"edelstenen": [
    ["diamant", "diamante"],
    ["briljant", "brillante"],
    ["robijn", "rubí"],
    ["saffier", "zafiro"],
    ["emerald", "esmeralda"],
    ["smaragd", "esmeralda"],
    ["amethist", "amatista"],
    ["topaas", "topacio"],
    ["toermalijn", "turmalina"],
    ["aquamarijn", "aguamarina"],
    ["granaat", "granate"],
    ["opaal", "ópalo"],
    ["peridoot", "peridoto"],
    ["citrine", "citrino"],
    ["turkoois", "turquesa"]
],

"groet": [
                ["hallo", "hola"],
                ["goeie morgen", "buenos días"],
                ["goeie middag", "buenas tardes"],
                ["goeie avond", "buenas noches"],
                ["tot ziens", "hasta luego"],
                ["dank je", "gracias"],
                ["graag gedaan (bali)", "de nada"],
                ["graag gedaan (java)", "no hay problema"],
                ["hoe is het", "¿qué tal?"],
                ["relax", "tranquilo nomás"],
                ["gewoon", "normal nomás"],
                ["geen gedoe", "no hace falta"],
                ["hoe is het met jou", "¿cómo estás tú?"]
            ],
            "omgang": [
                ["Hoe gaat het?", "¿Qué tal?"],
                ["Lang niet gezien!", "¡Mucho tiempo sin vernos!"],
                ["Wat doe jij tegenwoordig?", "¿Qué estás haciendo ahora?"],
                ["Hoe is het met je familie?", "¿Cómo está tu familia?"],
                ["Tot ziens!", "¡Hasta luego!"],
                ["Doe voorzichtig!", "¡Cuídate!"],
                ["Succes ermee!", "¡Ánimo!"],
                ["Leuk je te zien!", "¡Qué gusto verte!"],
                ["Tot snel!", "¡Hasta pronto!"],
                ["Pas op!", "¡Cuidado!"],
                ["Gefeliciteerd!", "¡Felicidades!"],
                ["Sorry, mijn fout!", "¡Perdón, error mío!"]
            ],

            "straat": [
                ["Pas op voor de auto!", "¡Cuidado con el coche!"],
                ["Kun je even opzij gaan?", "¿Puedes apartarte un momento?"],
                ["Waar is de halte?", "¿Dónde está la parada?"],
                ["Mag ik erlangs?", "¿Puedo pasar?"],
                ["Kijk uit voor de fiets!", "¡Cuidado con la bicicleta!"],
                ["Het is hier druk!", "¡Está muy concurrido aquí!"],
                ["Wacht even op groen!", "¡Espera la luz verde primero!"],
                ["Niet oversteken hier!", "¡No cruces por aquí!"],
                ["Linksaf", "Gira a la izquierda"],
                ["rechtsaf", "gira a la derecha"],
                ["Rechtdoor", "Todo recto nomás"],
                ["Is dit de goede kant?", "¿Es esta la dirección correcta?"],
                ["Rustig aan!", "¡Despacio!"]
            ],

    "voorzetsels": [
    ["aan", "en / a / hacia"],
    ["achter", "detrás de"],
    ["af", "desde / bajar"],
    ["behalve", "excepto"],
    ["beneden", "debajo de"],
    ["bij", "en / junto a / con"],
    ["binnen", "dentro de"],
    ["boven", "encima de / arriba de"],
    ["buiten", "fuera de"],
    ["door", "a través de / por"],
    ["in", "en / dentro de"],
    ["langs", "a lo largo de / por"],
    ["met", "con"],
    ["na", "después de"],
    ["naar", "hacia / a"],
    ["naast", "al lado de"],
    ["om", "alrededor de / para"],
    ["onder", "debajo de"],
    ["op", "sobre / en / encima de"],
    ["over", "sobre / acerca de"],
    ["per", "por"],
    ["sinds", "desde"],
    ["te", "en / a"],
    ["tegen", "contra / hacia"],
    ["tot", "hasta"],
    ["uit", "de / desde / fuera de"],
    ["van", "de / desde / perteneciente a"],
    ["voor", "para / delante de"],
    ["tussen", "entre"],
    ["zonder", "sin"]
],

    "werkwoorden": [
    ["zijn", "estar / ser / haber"],
    ["hebben", "tener / poseer"],
    ["doen", "hacer"],
    ["gaan", "ir"],
    ["komen", "venir"],
    ["willen", "querer / desear"],
    ["kunnen", "poder"],
    ["zeggen", "decir / afirmar"],
    ["maken", "hacer / crear"],
    ["kijken", "mirar / ver / ver televisión"],
    ["vragen", "preguntar"],
    ["weten", "saber"],
    ["moeten", "deber / tener que"],
    ["werken", "trabajar"],
    ["eten", "comer"],
    ["drinken", "beber / tomar"],
    ["zien", "ver"],
    ["vinden", "encontrar / sentir / opinar"],
    ["geven", "dar"],
    ["nemen", "tomar / coger"],
    ["beginnen", "empezar / comenzar"],
    ["eindigen", "terminar / acabar"],
    ["spreken", "hablar"],
    ["praten", "charlar / conversar"],
    ["lezen", "leer"],
    ["schrijven", "escribir"],
    ["helpen", "ayudar"],
    ["leren", "aprender / estudiar"],
    ["wonen", "vivir / residir"],
    ["slapen", "dormir"]
],

    "personen": [
                ["doktor", "médico / doctor"],
                ["verpleegster", "enfermera"],
                ["chirurg", "cirujano"],
                ["patient", "paciente"],
                ["tandarts", "dentista"],
                ["fysio", "fisioterapeuta"],
                ["apotheker", "farmacéutico"],
                ["masseur", "masajista"],
                ["anesthesist", "anestesista"]
            ],
            "dieren": [
                ["hond", "perro"],
                ["kat", "gato"],
                ["konijn", "conejo"],
                ["paard", "caballo"],
                ["koe", "vaca"],
                ["varken", "cerdo"],
                ["schaap", "oveja"],
                ["vis", "pez"],
                ["kip", "pollo / gallina"],
                ["olifant", "elefante"],
                ["tijger", "tigre"],
                ["aap", "mono"],
                ["leeuw", "león"]
            ],
            "vissen": [
                ["baars", "perca"],
                ["snoek", "lucioperca / lucio"],
                ["karper", "carpa"],
                ["paling", "anguila"],
                ["snoekbaars", "perca lucioperca"],
                ["voorn", "escardola"],
                ["brasem", "brema"],
                ["melkvis", "chancho"],
                ["meerval", "bagre"],
                ["reuzengurami", "gurami gigante"],
                ["tilapia", "tilapia"],
                ["Indische makreel", "caballa india"]
            ],

    "vogels": [
                ["koolmees", "carbonero común"],
                ["pimpelmees", "herrerillo"],
                ["huismus", "gorrión común"],
                ["roodborst", "petirrojo"],
                ["ekster", "urraca"],
                ["houtduif", "paloma torcaz"],
                ["merel", "mirlo"],
                ["mus", "gorrión"],
                ["winterkoning", "reyezuelo / troglodita"],
                ["duif", "paloma"]
            ],
            "zee_creaturen": [
                ["zeehond", "foca"],
                ["krab", "cangrejo"],
                ["garnaal", "camarón / gamba"],
                ["zeester", "estrella de mar"],
                ["kwal", "medusa"],
                ["kokkel", "almeja cockle"],
                ["mossel", "mejillón"],
                ["groene zeeschildpad", "tortuga verde"],
                ["karetschildpad", "tortuga carey"],
                ["doegong", "dugongo"],
                ["reuzenmanta", "mantarraya gigante"],
                ["walvishaai", "tiburón ballena"]
            ],
            "insecten": [
                ["lieveheersbeestje", "mariquita"],
                ["hommel", "abejorro"],
                ["bij", "abeja melífera"],
                ["wesp", "avispa"],
                ["huisvlieg", "mosca doméstica"],
                ["zweefvlieg", "mosca voladora / sírfido"],
                ["oorworm", "tijereta"],
                ["libelle", "libélula"],
                ["kakkerlak", "cucaracha"],
                ["mug", "mosquito"],
                ["mier", "hormiga"],
                ["vlinder", "mariposa"]
            ],

    "fruit": [
                ["appel", "manzana"],
                ["banaan", "plátano / banana"],
                ["sinaasappel", "naranja"],
                ["aardbei", "fresa"],
                ["peer", "pera"],
                ["druif", "uva"],
                ["kers", "cereza"],
                ["ananas", "piña"],
                ["mango", "mango"],
                ["citroen", "limón"],
                ["limoen", "lima"],
                ["meloen", "melón"]
             ],
             "kruiden": [
                ["basilicum", "albahaca"],
                ["koriander", "cilantro / coriandro"],
                ["munt", "menta"],
                ["dille", "eneldo"],
                ["tijm", "tomillo"],
                ["rozemarijn", "romero"],
                ["salie", "salvia"],
                ["dragon", "estragón"],
                ["bieslook", "cebollino"],
                ["citroen gras", "hierba de limón / lemongrass"],
                ["oregano", "orégano"],
                ["laurier", "laurel"]
             ],
             "groente": [
                ["wortel", "zanahoria"],
                ["ui", "cebolla"],
                ["tomaat", "tomate"],
                ["sla", "lechuga"],
                ["komkommer", "pepino"],
                ["aardappel", "patata / papa"],
                ["bloemkool", "coliflor"],
                ["broccoli", "brócoli"],
                ["spinazie", "espinaca"],
                ["knoflook", "ajo"],
                ["paprika", "pimiento / pimentón"],
                ["courgette", "calabacín / zucchini"]
             ],

    "specerijen": [
                ["kaneel", "canela"],
                ["kruidnagel", "clavo de olor"],
                ["nootmuskaat", "nuez moscada"],
                ["gember", "jengibre"],
                ["kurkuma", "cúrcuma"],
                ["komijn", "comino"],
                ["kardemom", "cardamomo"],
                ["peper", "pimienta / pimienta negra"],
                ["anijs", "anís estrellado"],
                ["foelie", "macis / flor de nuez moscada"],
                ["saffraan", "azafrán"],
                ["korianderzaad", "semilla de cilantro"]
             ],
            "kleuren": [
                ["rood", "rojo"],
                ["zwart", "negro"],
                ["kleur", "color"],
                ["blauw", "azul"],
                ["wit", "blanco"],
                ["oranje", "naranja"],
                ["paars", "morado / púrpura"],
                ["roze", "rosa"],
                ["groen", "verde"],
                ["geel", "amarillo"],
                ["bruin", "marrón"],
                ["grijs", "gris"]
            ],
            "exotic": [
                ["turquoise", "turquesa"],
                ["lila", "lila / morado claro"],
                ["magenta", "magenta"],
                ["indigo", "índigo"],
                ["paars", "morado oscuro"],
                ["fuchsia", "fucsia"],
                ["cyaan", "cian"],
                ["kobaltblauw", "azul cobalto"],
                ["saffier", "azul zafiro"],
                ["amethist", "morado amatista"],
                ["smaragd", "verde esmeralda"],
                ["roze koraal", "rosa coral"]
            ],

    "planten": [
                ["paardebloem", "diente de león"],
                ["geranium", "geranio"],
                ["zonnebloem", "girasol"],
                ["boterbloem", "botón de oro"],
                ["jasmijn", "jazmín"],
                ["hibiscus", "hibisco / cayena"],
                ["frangipani/plumeria", "frangipani / plumeria"],
                ["bougainville", "buganvilla / bougainvillea"],
                ["ixora", "ixora"],
                ["roos", "rosa"],
                ["chrysant", "crisantemo"]
            ],
            "bomen": [
                ["boom", "árbol"],
                ["eik", "roble"],
                ["beuk", "haya"],
                ["den", "pino"],
                ["spar", "abeto / picea"],
                ["berk", "abedul"],
                ["esdoorn", "arce"],
                ["kastanje", "castaño"],
                ["wilg", "sauce"],
                ["linde", "tilo"],
                ["populier", "álamo"],
                ["palm", "palmera"]
            ],
            "gebouw": [
                ["ziekenhuis", "hospital"],
                ["kliniek", "clínica"],
                ["dokterpraktijk", "consultorio médico"],
                ["apotheek", "farmacia"],
                ["spoedeisende hulp", "urgencias / servicio de emergencia"],
                ["polikliniek", "policlínica / consulta externa"],
                ["laboratorium", "laboratorio"],
                ["röntgenafdeling", "departamento de rayos X"],
                ["operatiekamer", "quirófano / sala de operaciones"],
                ["wachtkamer", "sala de espera"],
                ["kinderafdeling", "pediatría / sala de niños"],
                ["verloskamer", "sala de partos"]
            ],

    "symptomen": [
                ["koorts", "fiebre"],
                ["hoofdpijn", "dolor de cabeza"],
                ["hoesten", "tos"],
                ["keelpijn", "dolor de garganta"],
                ["misselijk", "náuseas"],
                ["braken", "vomitar"],
                ["diarree", "diarrea"],
                ["verstopping", "estreñimiento"],
                ["duizelig", "mareado / vértigo"],
                ["kortademig", "dificultad para respirar / falta de aire"],
                ["moe", "cansado / fatigado"],
                ["zweten", "sudoración / sudar"]
            ],
            "klachten": [
                ["pijn", "dolor / malestar"],
                ["jeuk", "picazón / comezón"],
                ["zwelling", "hinchazón"],
                ["bloeding", "sangrado / hemorragia"],
                ["uitslag", "erupción / sarpullido"],
                ["stijf", "rigidez / tieso"],
                ["zwak", "débil"],
                ["ademhaling", "respiración"],
                ["hartkloppingen", "palpitaciones del corazón"],
                ["brandend gevoel", "sensación de ardor"],
                ["druk op de borst", "presión en el pecho"],
                ["tintelingen", "hormigueo"],
                ["kramp", "calambre / espasmo"]
            ],
            "medicijnen": [
                ["paracetamol", "paracetamol"],
                ["ibuprofen", "ibuprofeno"],
                ["amoxicilline", "amoxicilina"],
                ["pijnstiller", "analgésico / calmante del dolor"],
                ["antibiotica", "antibiótico"],
                ["hoestsiroop", "jarabe para la tos"],
                ["vitamine", "vitamina"],
                ["pleister", "curita / apósito adhesivo"],
                ["zalf", "pomada / ungüento"],
                ["tabletten", "tabletas / pastillas"],
                ["injectie", "inyección"],
                ["druppels", "gotas"]
            ],

    "lichaamsdelen": [
                ["hand", "mano"],
                ["voet", "pie"],
                ["arm", "brazo"],
                ["been (incl. voet)", "pierna (incl. pie)"],
                ["been (excl. voet)", "pierna (excl. pie)"],
                ["vinger", "dedo"],
                ["teen", "dedo del pie"],
                ["hoofd", "cabeza"],
                ["hals", "cuello"],
                ["neus", "nariz"],
                ["buik", "abdomen / barriga"],
                ["borst", "pecho"],
                ["elleboog", "codo"],
                ["kuit", "pantorrilla"],
                ["oor", "oreja"],
                ["mond", "boca"],
                ["tong", "lengua"],
                ["pols", "muñeca"],
                ["schouder", "hombro"],
                ["enkel", "tobillo"],
                ["knie", "rodilla"]
            ],
            "vliegveld": [
                ["vliegveld", "aeropuerto"],
                ["vliegtuig", "avión"],
                ["check-in", "check-in / facturación"],
                ["bagage", "equipaje"],
                ["rookruimte", "área para fumadores"],
                ["paspoort", "pasaporte"],
                ["gate", "puerta / puerta de embarque"],
                ["vertrek", "salidas / partidas"],
                ["aankomst", "llegadas"],
                ["douane", "aduana"],
                ["veiligheidscontrole", "control de seguridad"],
                ["boarding pass", "tarjeta de embarque"],
                ["wachtruimte", "sala de espera"],
                ["stewardes", "azafata / auxiliar de vuelo"],
                ["steward", "azafato / auxiliar de vuelo"],
                ["belasting vrij", "libre de impuestos / duty free"],
                ["bagageband", "cinta transportadora de equipaje"]
            ],

    "ov": [
                ["openbaar vervoer", "transporte público"],
                ["bus", "autobús / bus"],
                ["tram", "tranvía"],
                ["metro", "metro / subterráneo"],
                ["halte", "parada"],
                ["kaartje", "billete / ticket"],
                ["chauffeur", "conductor / chofer"],
                ["halteplaats", "paradero / parada"],
                ["lijn", "línea / ruta"],
                ["retour", "ida y vuelta"],
                ["abonnement", "abono / suscripción"],
                ["omwisselen", "transbordo / cambiar"]
            ],
            "station": [
                ["station", "estación"],
                ["trein", "tren"],
                ["perron", "andén / plataforma"],
                ["treinkaartje", "billete de tren"],
                ["spoor", "vía / riel"],
                ["loket", "taquilla / ventanilla"],
                ["vertrektijd", "hora de salida"],
                ["aankomsttijd", "hora de llegada"],
                ["spoorweg", "ferrocarril / vía férrea"],
                ["bagagekluis", "consigna / taquilla para equipaje"],
                ["informatiebalie", "mostrador de información"],
                ["overstap", "transbordo / cambio de tren"]
            ],
            "smaken": [
                ["zoet", "dulce"],
                ["zout", "salado"],
                ["zuur", "ácido / agrio"],
                ["bitter", "amargo"],
                ["pittig/scherp", "picante / picante fuerte"],
                ["pikant", "sazonado / especiado"],
                ["kruidig", "aromático / con especias"],
                ["fris", "fresco"],
                ["zacht", "suave / blando"],
                ["romig", "cremoso"],
                ["hartig", "sabroso / salado sabroso"],
                ["wrang", "astringente / acerbo"]
            ],
            "keuken": [
                ["koken", "cocinar"],
                ["recept", "receta"],
                ["pan", "olla / cacerola"],
                ["koekenpan", "sartén"],
                ["oven", "horno"],
                ["snijden", "cortar"],
                ["roeren", "revolver / remover"],
                ["bakken", "freír / hornear"],
                ["koken", "hervir"],
                ["kruiden", "especias / condimentos"],
                ["zout", "sal"],
                ["peper", "pimienta"]
            ],

    "restaurant": [
                ["restaurant", "restaurante"],
                ["menu", "menú"],
                ["ober", "camarero / mesero"],
                ["bestellen", "pedir / ordenar"],
                ["rekening", "cuenta / factura"],
                ["fooi", "propina"],
                ["tafel", "mesa"],
                ["stoel", "silla"],
                ["kaart", "carta / menú"],
                ["reserveren", "reservar"],
                ["afhalen", "para llevar / para llevarse"],
                ["serveren", "servir"]
            ],
            "dinner": [
                ["diner", "cena"],
                ["hoofdgerecht", "plato principal"],
                ["bijgerecht", "acompañamiento / guarnición"],
                ["soep", "sopa"],
                ["salade", "ensalada"],
                ["rijst", "arroz"],
                ["vlees", "carne"],
                ["vis", "pescado"],
                ["groente", "verdura / verduras"],
                ["saus", "salsa"],
                ["eten", "comer"],
                ["genieten", "disfrutar / gozar"]
            ],
            "ontbijt": [
                ["ontbijt", "desayuno"],
                ["brood", "pan"],
                ["boter", "mantequilla"],
                ["kaas", "queso"],
                ["ei", "huevo"],
                ["jam", "mermelada / confitura"],
                ["koffie", "café"],
                ["thee", "té"],
                ["croissant", "croissant"],
                ["yoghurt", "yogur"],
                ["muesli", "muesli / granola"],
                ["pannenkoek", "panqueque / tortita"]
            ],

    "toetjes": [
                ["toetje", "postre / dessert"],
                ["ijs", "helado"],
                ["pudding", "pudín"],
                ["taart", "tarta"],
                ["cake", "bizcocho / pastel"],
                ["chocolade", "chocolate"],
                ["fruit", "fruta"],
                ["yoghurt", "yogur"],
                ["flan", "flan / caramelo"],
                ["crème brûlée", "crema brûlée"],
                ["tiramisu", "tiramisú"],
                ["gebak", "pastelitos / bollería"]
            ],
            "snoep": [
                ["snoep", "caramelos / dulces"],
                ["chocolade", "chocolate"],
                ["drop", "regaliz / caramelos ácidos"],
                ["gom", "chicle / goma de mascar"],
                ["lolly", "piruleta / chupetín"],
                ["marshmallow", "malvavisco"],
                ["gummybeer", "ositos de goma"],
                ["zuurtje", "caramelo ácido"],
                ["toffees", "toffee / caramelo blando"],
                ["pepermunt", "caramelo de menta"],
                ["kauwgom", "chicle"],
                ["zuurtjes", "caramelos ácidos"]
            ],
            "betaal_pin": [
                ["pinnen", "pagar con tarjeta"],
                ["pincode", "código PIN"],
                ["pasje", "tarjeta ATM / débito"],
                ["automaat", "cajero automático / ATM"],
                ["saldo", "saldo"],
                ["intoetsen", "ingresar / teclear"],
                ["opnemen", "retirar efectivo"],
                ["chip", "chip"],
                ["contactloos", "sin contacto / pago contactless"],
                ["limiet", "límite"],
                ["bevestigen", "confirmar"],
                ["betalen", "pagar"],
                ["prijs", "precio"],
                ["transactie", "transacción"],
                ["kosten", "coste / cargos"]
            ],

    "betaal_cash": [
                ["contant", "efectivo / en efectivo"],
                ["geld", "dinero"],
                ["briefje", "billete"],
                ["munten", "monedas"],
                ["wisselgeld", "cambio / vuelto"],
                ["betalen", "pagar"],
                ["kassa", "caja / cajero"],
                ["portemonnee", "billetera / cartera"],
                ["100 euro", "cien euros"],
                ["fooi", "propina"],
                ["pinnen of cash?", "¿pagar con tarjeta o en efectivo?"],
                ["prijs", "precio"],
                ["korting", "descuento"],
                ["kleingeld", "monedas sueltas / cambio pequeño"]
            ],
            "rekening": [
                ["rekening", "cuenta"],
                ["bankrekening", "cuenta bancaria"],
                ["spaarrekening", "cuenta de ahorros"],
                ["betaalrekening", "cuenta corriente"],
                ["rente", "interés"],
                ["saldo", "saldo"],
                ["overschrijving", "transferencia"],
                ["incasso", "domiciliación / débito automático"],
                ["afschrift", "extracto bancario"],
                ["IBAN", "IBAN"],
                ["BIC", "código BIC / SWIFT"],
                ["kosten", "comisiones / gastos administrativos"]
            ],
            "crypto": [
                ["cryptocurrency", "criptomoneda"],
                ["bitcoin", "bitcoin"],
                ["ethereum", "ethereum"],
                ["wallet", "billetera cripto / monedero"],
                ["exchange", "exchange / plataforma de intercambio"],
                ["blockchain", "blockchain / cadena de bloques"],
                ["mining", "minería"],
                ["koers", "cotización / precio"],
                ["token", "token"],
                ["private key", "clave privada"],
                ["seed phrase", "frase semilla / frase de recuperación"],
                ["staking", "staking"]
            ],

    "fiets": [
                ["fiets", "bicicleta"],
                ["fietsen", "andar en bicicleta / pedalear"],
                ["fietser", "ciclista"],
                ["fietshelm", "casco de bicicleta"],
                ["fietsbel", "timbre de bicicleta"],
                ["fietspad", "carril bici / vía ciclista"],
                ["band lek", "pinchazo / neumático desinflado"],
                ["pomp", "bomba / inflador"],
                ["slot", "candado / cerradura de bicicleta"],
                ["bagagedrager", "portabultos / portaequipajes"],
                ["fietslamp", "luz de bicicleta"],
                ["zadel", "sillín"]
            ],
            "autos": [
                ["auto", "coche / automóvil"],
                ["rijden", "conducir"],
                ["chauffeur", "conductor / chofer"],
                ["benzine", "gasolina"],
                ["diesel", "diésel"],
                ["parkeren", "aparcar / estacionar"],
                ["stuur", "volante"],
                ["rem", "freno"],
                ["gaspedaal", "acelerador"],
                ["koppeling", "embrague"],
                ["kofferbak", "maletero / baúl"],
                ["raam", "ventana"]
            ],
            "voetganger": [
                ["voetganger", "peatón"],
                ["lopen", "caminar"],
                ["zebrapad", "paso de cebra / cruce peatonal"],
                ["stoep", "acera / banqueta"],
                ["oversteekplaats", "paso peatonal"],
                ["verkeerslicht", "semáforo"],
                ["rood licht", "luz roja"],
                ["groen licht", "luz verde"],
                ["oversteken", "cruzar"],
                ["trottoir", "acera / banqueta"],
                ["voetpad", "vía peatonal / camino peatonal"]
            ],

    "vvmiddel": [
                ["voertuig", "vehículo"],
                ["bromfiets", "motocicleta automática / scooter"],
                ["motor", "moto / motocicleta"],
                ["auto", "coche / automóvil"],
                ["fiets", "bicicleta"],
                ["step", "patineta / monopatín"],
                ["bus", "autobús"],
                ["trein", "tren"],
                ["vliegtuig", "avión"],
                ["brommerkarretje", "mototaxi con sidecar"],
                ["paardewagen", "carro de caballos / andong"],
                ["minibusjes", "minibús público / angkot"],
                ["taxi", "taxi"],
                ["scooter", "scooter"],
                ["vrachtwagen", "camión"],
                ["ambulance", "ambulancia"],
                ["brandweerauto", "camión de bomberos"],
                ["politieauto", "coche de policía"]
            ],
            "route": [
                ["route", "ruta"],
                ["weg", "carretera / camino"],
                ["snelweg", "autopista / carretera de peaje"],
                ["afslag", "salida / intersección"],
                ["richting", "dirección"],
                ["rechtsaf", "gira a la derecha"],
                ["linksaf", "gira a la izquierda"],
                ["rechtdoor", "recto"],
                ["omleiding", "desvío"],
                ["navigatie", "navegación"],
                ["kaart", "mapa"],
                ["gps", "GPS"]
            ],
            "regels": [
                ["verkeersregels", "normas de tráfico"],
                ["snelheidslimiet", "límite de velocidad"],
                ["stoplicht", "semáforo"],
                ["voorrang", "prioridad"],
                ["inhaalverbod", "prohibido adelantar"],
                ["riem", "cinturón de seguridad"],
                ["helm", "casco"],
                ["boete", "multa"],
                ["rijbewijs", "licencia de conducir / carnet"],
                ["parkeerverbod", "prohibido estacionar"],
                ["fietspad verplicht", "obligatorio carril bici"],
                ["rechts rijden", "conducir por la derecha"]
            ],
            "winkelen": [
                ["shoppen", "comprar / ir de compras"],
                ["kleren kopen", "comprar ropa"],
                ["uitverkoop", "rebajas / liquidación"],
                ["winkelcentrum", "centro comercial"],
                ["pashokje", "probador"],
                ["kassa", "caja / cajero"],
                ["bonnetje", "recibo / ticket"],
                ["retour", "devolución"],
                ["grootte", "talla / tamaño"],
                ["korting", "descuento"],
                ["winkelwagen", "carrito de compras"],
                ["betalen", "pagar"]
            ],
            "mall": [
                ["winkelcentrum", "centro comercial / mall"],
                ["bioscoop", "cine"],
                ["foodcourt", "patio de comidas / food court"],
                ["lift", "ascensor / escaleras mecánicas"],
                ["parkeren", "estacionar"],
                ["toilet", "baño / servicios"],
                ["atrium", "atrio"],
                ["fontein", "fuente"],
                ["speelplaats", "zona de juegos infantiles"],
                ["bioscoopticket", "entrada al cine"],
                ["promotie", "promoción"],
                ["klantenservice", "atención al cliente"]
            ],
            "toko": [
                ["winkel", "tienda"],
                ["kruidenier", "tienda de ultramarinos / abarrotes"],
                ["markt", "mercado"],
                ["supermarkt", "supermercado"],
                ["minimarkt", "tienda de conveniencia / minimercado"],
                ["kassa", "caja"],
                ["prijs", "precio"],
                ["rekening", "recibo / factura"],
                ["plastic zak", "bolsa de plástico"],
                ["vers", "fresco"],
                ["pakket", "paquete"],
                ["afrekenen", "pagar en caja"]
            ],
            "warung": [
                ["eetstalletje", "puesto de comida / warung"],
                ["koffie", "café"],
                ["thee", "té"],
                ["nasi goreng", "arroz frito"],
                ["mie goreng", "fideos fritos"],
                ["saté", "satay / brochetas"],
                ["soep", "sopa"],
                ["ijs", "helado"],
                ["sigaret", "cigarrillo"],
                ["plastic stoel", "silla de plástico"],
                ["take away", "para llevar / empaquetado"],
                ["rekening", "cuenta"]
            ],
            "restaurant": [
                ["restaurant", "restaurante"],
                ["menu", "menú"],
                ["ober", "camarero / mesero"],
                ["bestellen", "pedir"],
                ["rekening", "cuenta / factura"],
                ["fooi", "propina"],
                ["voorgerecht", "entrante / aperitivo"],
                ["hoofdgerecht", "plato principal"],
                ["nagerecht", "postre / dessert"],
                ["drinken", "bebida"],
                ["reserveren", "reservar"],
                ["tafel", "mesa"]
            ],

    "clubbing": [
                ["discotheek", "discoteca / club nocturno"],
                ["dansvloer", "pista de baile"],
                ["dj", "disc jockey / DJ"],
                ["muziek", "música"],
                ["drankje", "bebida"],
                ["feest", "fiesta / party"],
                ["bouncer", "portero / vigilante de puerta"],
                ["cover charge", "entrada / costo de entrada"],
                ["lightshow", "espectáculo de luces"],
                ["afterparty", "after / after party"],
                ["crowd", "multitud / gentío"],
                ["chill", "relajado / tranqui"]
            ],
            "concert": [
                ["concert", "concierto"],
                ["kaartje", "entrada / boleto"],
                ["podium", "escenario"],
                ["band", "banda / grupo"],
                ["zanger", "cantante"],
                ["gitaar", "guitarra"],
                ["drum", "batería"],
                ["publiek", "público"],
                ["applaus", "aplauso"],
                ["encore", "encore / bis"],
                ["festival", "festival"],
                ["geluid", "sonido"]
            ],
            "kroeg": [
                ["kroeg", "bar / pub"],
                ["biertje", "cerveza"],
                ["pils", "cerveza pilsner"],
                ["jenever", "ginebra / jenever"],
                ["borrel", "copas / tomar algo"],
                ["barkeeper", "bartender / barman"],
                ["kruk", "taburete de bar"],
                ["hapje", "picoteo / tapas"],
                ["biljart", "billar"],
                ["darts", "dardos"],
                ["muziekje", "música de fondo"],
                ["laat", "tarde / noche"]
            ],
            "luisteren": [
                ["luisteren", "escuchar"],
                ["muziek luisteren", "escuchar música"],
                ["playlist", "lista de reproducción"],
                ["koptelefoon", "auriculares / headphones"],
                ["oortjes", "auriculares in-ear / earbuds"],
                ["volume", "volumen"],
                ["nummer", "canción / tema"],
                ["album", "álbum"],
                ["artiest", "artista"],
                ["streaming", "streaming"],
                ["downloaden", "descargar"],
                ["afspelen", "reproducir / poner"]
            ],
            "instrumenten": [
                ["gitaar", "guitarra"],
                ["piano", "piano"],
                ["drum", "batería"],
                ["viool", "violín"],
                ["basgitaar", "bajo eléctrico"],
                ["fluit", "flauta"],
                ["trompet", "trompeta"],
                ["saxfoon", "saxofón"],
                ["keyboard", "teclado"],
                ["ukulele", "ukulele"],
                ["harmonica", "armónica"],
                ["cello", "violonchelo"]
            ],

    "audio": [
                ["geluid", "sonido"],
                ["luidspreker", "altavoz / parlante"],
                ["microfoon", "micrófono"],
                ["geluidskwaliteit", "calidad de sonido"],
                ["stereo", "estéreo"],
                ["surround", "surround"],
                ["mp3", "mp3"],
                ["wav", "wav"],
                ["bitrate", "bitrate"],
                ["versterker", "amplificador"],
                ["recorder", "grabadora"],
                ["podcast", "podcast"]
            ],
            "hifi": [
                ["hifi", "hi-fi"],
                ["versterker", "amplificador"],
                ["luidspreker", "altavoz hi-fi"],
                ["platenspeler", "tocadiscos"],
                ["cd-speler", "reproductor de CD"],
                ["dac", "DAC"],
                ["analoog", "analógico"],
                ["digitaal", "digital"],
                ["vinyl", "vinilo"],
                ["tube", "válvula / tubo de vacío"],
                ["tuner", "sintonizador"],
                ["receiver", "receptor"]
            ],
            "informeel": [
                ["yo", "yo / bro"],
                ["hé", "hé / ey"],
                ["gaaf", "guay / genial / chévere"],
                ["chill", "tranqui / relajado"],
                ["lekker", "rico / chévere / guay"],
                ["Ik geniet even van de gezelligheid, super leuk!", "Estoy disfrutando del rollo de estar juntos, ¡qué guay!"],
                ["vet", "brutal / la hostia"],
                ["niks aan de hand", "tranqui / no pasa nada"],
                ["doei", "chau / adiós"],
                ["tot zo", "hasta ahora / en un rato"],
                ["later", "luego / más tarde"],
                ["oké", "vale / ok"],
                ["tuurlijk", "claro / por supuesto"]
            ],
            "formeel": [
                ["goedemorgen", "buenos días"],
                ["goedemiddag", "buenas tardes"],
                ["goedenavond", "buenas noches"],
                ["dank u wel", "muchas gracias"],
                ["alstublieft", "por favor / aquí tiene"],
                ["excuseer mij", "disculpe / perdón"],
                ["met wie spreek ik?", "¿con quién hablo?"],
                ["u spreekt met", "le habla"],
                ["tot ziens", "hasta luego"],
                ["prettige dag", "que tenga un buen día"],
                ["graag gedaan", "de nada"],
                ["Heel fijn om van de warmte van samen zijn met familie en vrienden te genieten", "Es muy agradable disfrutar de la calidez de estar juntos con familia y amigos"],
                ["mag ik u iets vragen?", "¿puedo hacerle una pregunta?"]
            ],
            "vrienden": [
                ["vriend", "amigo"],
                ["beste vriend", "mejor amigo / amigo del alma"],
                ["kameraad", "camarada / compañero"],
                ["vanavond bij elkaar met vrienden", "Esta noche nos juntamos con los amigos"],
                ["genieten van het geklets tot diep in de nacht", "disfrutando de la charla hasta altas horas"],
                ["maatje", "colega / compa"],
                ["buddy", "amigo / pana"],
                ["hangen", "quedar / vaguear"],
                ["chillen", "relajarse juntos / pasar el rato"],
                ["feestje", "fiestecita / party pequeña"],
                ["uitgaan", "salir / ir de fiesta"],
                ["appje", "mensaje / chat"],
                ["belletje", "llamada rápida"],
                ["afspreken", "quedar / hacer planes"]
            ],

    "straat": [
                ["straat", "calle"],
                ["stoep", "acera / banqueta"],
                ["zebrapad", "paso de cebra"],
                ["verkeerslicht", "semáforo"],
                ["auto", "coche / auto"],
                ["fiets", "bicicleta"],
                ["voetganger", "peatón"],
                ["bord", "señal / letrero"],
                ["lantaarnpaal", "farola / poste de luz"],
                ["vuilnisbak", "papelera / basurero"],
                ["straatnaambord", "placa de calle / letrero de nombre de calle"],
                ["oversteekplaats", "paso peatonal / cruce"]
            ],
            "speelgoed": [
                ["pop", "muñeca"],
                ["beer", "oso de peluche / teddy bear"],
                ["auto", "coche de juguete / autito"],
                ["bal", "pelota"],
                ["lego", "lego"],
                ["puzzel", "rompecabezas / puzzle"],
                ["blok", "bloque de construcción / cubo de juguete"],
                ["trein", "tren de juguete"],
                ["vliegtuig", "avión de juguete"],
                ["knuffel", "peluche / muñeco de peluche"],
                ["poppenhuis", "casa de muñecas"],
                ["kleurboek", "libro para colorear"]
            ],
            "e-games": [
                ["spel", "juego"],
                ["videogame", "videojuego"],
                ["computer", "computadora / ordenador"],
                ["telefoon", "teléfono / celular"],
                ["controller", "control / mando / joystick"],
                ["level", "nivel"],
                ["punten", "puntos / puntaje"],
                ["multiplayer", "multijugador"],
                ["online", "en línea / online"],
                ["karakter", "personaje"],
                ["win", "ganar"],
                ["verlies", "perder"]
            ],
            "board-games": [
                ["bordspel", "juego de mesa"],
                ["schaken", "ajedrez"],
                ["dammen", "damas"],
                ["monopoly", "monopolio"],
                ["mens erger je niet", "serpientes y escaleras"],
                ["kaarten", "cartas"],
                ["dobbelsteen", "dado"],
                ["strategie", "estrategia"],
                ["beurt", "turno"],
                ["winnaar", "ganador"],
                ["speler", "jugador"],
                ["bord", "tablero"]
            ],

    "sauna": [
                ["sauna", "sauna"],
                ["stoomcabine", "cabina de vapor"],
                ["hitte", "calor"],
                ["relaxen", "relajarse"],
                ["zweten", "sudar"],
                ["handdoek", "toalla"],
                ["koud bad", "baño frío"],
                ["stoombad", "baño de vapor caliente"],
                ["saunagang", "sesión de sauna"],
                ["rustruimte", "sala de descanso"],
                ["infuus", "infusión / beber mucha agua"],
                ["saunamuts", "gorro de sauna"]
            ],
            "therapie": [
                ["therapie", "terapia"],
                ["massage", "masaje"],
                ["aromatherapie", "aromaterapia"],
                ["yoga", "yoga"],
                ["meditatie", "meditación"],
                ["reflexologie", "reflexología"],
                ["acupunctuur", "acupuntura"],
                ["reiki", "reiki"],
                ["ontspanning", "relajación"],
                ["stress", "estrés"],
                ["ademhaling", "respiración"],
                ["mindfulness", "atención plena / mindfulness"]
            ],
            "thuis": [
                ["thuis", "en casa"],
                ["relaxen", "relajarse"],
                ["bank", "sofá"],
                ["genieten van (formeel)", "disfrutar de"],
                ["genieten van (informeel)", "disfrutar / gozar de"],
                ["thee", "té"],
                ["samen zijn", "estar juntos"],
                ["samenwonen", "convivir"],
                ["boek", "libro"],
                ["muziek", "música"],
                ["kaars", "vela"],
                ["bad", "baño"],
                ["film kijken", "ver una película"],
                ["slapen", "dormir"],
                ["rustig", "tranquilo"],
                ["comfortabel", "cómodo"]
            ],
            "met_familie": [
                ["familie", "familia"],
                ["samen", "juntos"],
                ["spelletje", "jugar un juego"],
                ["filmavond", "noche de cine"],
                ["eten", "comer juntos"],
                ["vreugde", "alegría"],
                ["geluk", "felicidad"],
                ["liefde", "amor"],
                ["tegenspoed", "dificultades / adversidad"],
                ["verdriet", "tristeza"],
                ["praten", "charlar / conversar"],
                ["in tijden van", "en tiempos de"],
                ["samen in voor en tegenspoed", "Juntos en las buenas y en las malas"],
                ["knuffelen", "abrazar / abrazos"],
                ["uitstapje", "excursión juntos / salida familiar"],
                ["herinnering", "recuerdo"],
                ["lachen", "reír"],
                ["rustig", "tranquilos juntos"],
                ["thuis", "en casa juntos"]
            ],

    "interieur": [
                ["dashboard", "tablero / salpicadero"],
                ["stuurwiel", "volante"],
                ["stoel", "asiento"],
                ["bank", "asiento trasero / banqueta trasera"],
                ["veiligheidsgordel", "cinturón de seguridad"],
                ["airbag", "airbag / bolsa de aire"],
                ["handschoenenvak", "guantera / compartimento del tablero"],
                ["pook", "palanca de cambios / palanca de velocidades"],
                ["pedalen", "pedales"],
                ["raam", "ventana"],
                ["spiegel", "espejo retrovisor"],
                ["zonneklep", "parasol / visera solar"]
            ],
            "onderdelen": [
                ["motor", "motor"],
                ["accu", "batería / acumulador"],
                ["rem", "freno"],
                ["band", "neumático / llanta"],
                ["velg", "llanta / rin"],
                ["uitlaat", "escape / tubo de escape"],
                ["radiator", "radiador"],
                ["olie", "aceite"],
                ["filter", "filtro"],
                ["bougie", "bujía"],
                ["distributieriem", "correa de distribución / correa de tiempo"],
                ["schokdemper", "amortiguador"]
            ],
            "metalen": [
                ["ijzer", "hierro"],
                ["staal", "acero"],
                ["aluminium", "aluminio"],
                ["koper", "cobre"],
                ["lood", "plomo"],
                ["zink", "zinc"],
                ["tin", "estaño"],
                ["nikkel", "níquel"],
                ["chroom", "cromo"],
                ["magnesium", "magnesio"],
                ["titanium", "titanio"],
                ["goud", "oro"],
                ["zilver", "plata"],
                ["brons", "bronce"],
                ["puur goud", "oro puro"]
            ],
            "surf": [
                ["surfen", "surfear"],
                ["surfplank", "tabla de surf"],
                ["golven", "olas"],
                ["big wave", "ola grande"],
                ["shortboard", "tabla corta"],
                ["longboard", "tabla larga"],
                ["leash", "cordón / correa de seguridad"],
                ["wax", "cera para tabla"],
                ["surfspot", "spot de surf / lugar para surfear"],
                ["drop in", "entrar en la ola"],
                ["wipeout", "caerse de la ola"],
                ["spot", "lugar / spot"],
                ["board", "tabla"],
                ["golf", "ola"],
                ["zee", "mar"],
                ["strand", "playa"],
                ["barrel", "tubo / barrel"],
                ["dude", "tío / colega"]
            ],

    "voetbal": [
                ["voetbal", "fútbol"],
                ["gras", "césped / hierba"],
                ["wedstrijd", "partido"],
                ["doel", "portería / arco"],
                ["speler", "jugador"],
                ["doelman", "portero / arquero"],
                ["scheidsrechter", "árbitro"],
                ["goal", "gol"],
                ["penalty", "penalti / penal"],
                ["vrije trap", "tiro libre"],
                ["corner", "córner / saque de esquina"],
                ["kaart", "tarjeta"],
                ["fluiten", "silbato"]
            ],
            "netjes": [
                ["pak", "traje y pantalón"],
                ["stropdas", "corbata"],
                ["overhemd", "camisa"],
                ["blazer", "blazer"],
                ["rok", "falda"],
                ["jurk", "vestido"],
                ["pumps", "zapatos de tacón alto"],
                ["kostuum", "traje completo"],
                ["vest", "chaleco"],
                ["das", "corbata"],
                ["manchetknopen", "gemelos / botones de puño"],
                ["riem", "cinturón"]
            ],
            "gewoon": [
                ["spijkerbroek", "vaqueros / jeans"],
                ["T-shirt", "camiseta"],
                ["trui", "jersey / suéter"],
                ["hoodie", "sudadera con capucha"],
                ["sneaker", "zapatillas deportivas / sneakers"],
                ["short", "pantalones cortos / shorts"],
                ["shirt", "camisa casual"],
                ["jurk", "vestido casual"],
                ["legging", "leggings"],
                ["joggingbroek", "pantalones de chándal / jogging"],
                ["top", "top / blusa"],
                ["vest", "chaqueta ligera / cárdigan"]
            ],
            "opgedirkt": [
                ["high heels", "tacones altos"],
                ["cocktailjurk", "vestido de cóctel"],
                ["smoking", "esmoquin / smoking"],
                ["stropdas", "corbata"],
                ["make-up", "maquillaje"],
                ["juwelen", "joyas"],
                ["kleding", "ropa elegante / lujosa"],
                ["avondkleding", "ropa de noche / atuendo de gala"],
                ["glitter", "brillo / lentejuelas"],
                ["kralen", "perlas / cuentas"],
                ["stiletto", "stiletto"],
                ["clutch", "clutch / bolso de mano pequeño"]
            ],
            "schoenen": [
                ["schoenen", "zapatos"],
                ["sneaker", "zapatillas deportivas"],
                ["laarzen", "botas"],
                ["sandalen", "sandalias"],
                ["hakken", "tacones"],
                ["klompen", "zuecos"],
                ["slippers", "chanclas / sandalias de dedo"],
                ["pumps", "zapatos de tacón alto"],
                ["sportschoenen", "zapatillas deportivas"],
                ["loafers", "mocasines / loafers"],
                ["sneakers", "zapatillas / sneakers"],
                ["schoenendoos", "caja de zapatos"]
            ],

    "1_tot_10": [
                ["één", "uno"],
                ["twee", "dos"],
                ["drie", "tres"],
                ["vier", "cuatro"],
                ["vijf", "cinco"],
                ["zes", "seis"],
                ["zeven", "siete"],
                ["acht", "ocho"],
                ["negen", "nueve"],
                ["tien", "diez"],
                ["nul", "cero"],
                ["plus", "más"]
            ],
            "grote_cijfers": [
                ["honderd", "cien"],
                ["duizend", "mil"],
                ["tienduizend", "diez mil"],
                ["honderdduizend", "cien mil"],
                ["miljoen", "millón"],
                ["tien miljoen", "diez millones"],
                ["honderd miljoen", "cien millones"],
                ["miljard", "mil millones"],
                ["biljoen", "billón"],
                ["eerste", "primero"],
                ["tweede", "segundo"],
                ["derde", "tercero"]
            ],
            "wiskunde": [
                ["plus", "más"],
                ["min", "menos"],
                ["keer", "por / multiplicado por"],
                ["delen", "dividido por"],
                ["gelijk", "igual a"],
                ["som", "suma"],
                ["verschil", "diferencia"],
                ["product", "producto"],
                ["quotiënt", "cociente"],
                ["breuk", "fracción"],
                ["procent", "porcentaje"],
                ["vierkant", "cuadrado"]
            ],
            "tv": [
                ["televisie", "televisión"],
                ["tv", "TV"],
                ["programma", "programa"],
                ["zender", "canal"],
                ["afstandsbediening", "control remoto"],
                ["kanaal", "canal de TV"],
                ["series", "serie"],
                ["nieuws", "noticias"],
                ["film", "película"],
                ["realityshow", "reality show / programa de telerrealidad"],
                ["reclame", "anuncio / publicidad"],
                ["smart TV", "TV inteligente / smart TV"]
            ],
            "movies": [
                ["film", "película"],
                ["bioscoop", "cine"],
                ["actiefilm", "película de acción"],
                ["komedie", "comedia"],
                ["drama", "drama"],
                ["horror", "terror / horror"],
                ["thriller", "thriller / suspenso"],
                ["animatie", "animación"],
                ["documentaire", "documental"],
                ["trailer", "tráiler / avance"],
                ["acteur", "actor"],
                ["regisseur", "director"]
            ],
            "soorten": [
                ["weer", "clima / tiempo"],
                ["zonnig", "soleado"],
                ["bewolkt", "nublado"],
                ["regen", "lluvia"],
                ["onweer", "tormenta / trueno"],
                ["mist", "niebla"],
                ["wind", "viento"],
                ["sneeuw", "nieve"],
                ["hagel", "granizo"],
                ["storm", "tormenta / tempestad"],
                ["warm", "caluroso"],
                ["koud", "frío"]
            ],

    "klimaat": [
                ["klimaat", "clima"],
                ["tropisch", "tropical"],
                ["mediterraan", "mediterráneo"],
                ["continentaal", "continental"],
                ["polair", "polar"],
                ["woestijn", "desierto"],
                ["regenwoud", "selva tropical / bosque lluvioso"],
                ["gemiddelde temperatuur", "temperatura media / promedio"],
                ["neerslag", "precipitación"],
                ["seizoen", "estación"],
                ["droog", "seco"],
                ["vochtig", "húmedo"]
            ],
            "baan": [
                ["baan", "empleo / trabajo"],
                ["werk", "trabajo"],
                ["sollicitatie", "solicitud de empleo / postulación"],
                ["cv", "CV / currículum vitae"],
                ["salaris", "salario"],
                ["contract", "contrato"],
                ["vakantie", "vacaciones"],
                ["overwerk", "horas extras"],
                ["collega", "compañero de trabajo / colega"],
                ["baas", "jefe"],
                ["ontslag", "despido"],
                ["pensioen", "jubilación / pensión"]
            ],
            "hout": [
                ["hout", "madera"],
                ["zaag", "sierra"],
                ["hamer", "martillo"],
                ["spijker", "clavo"],
                ["schroef", "tornillo"],
                ["boor", "taladro"],
                ["schuurpapier", "lija"],
                ["lijm", "pegamento / cola"],
                ["verf", "pintura"],
                ["beitel", "cincel"],
                ["meetlint", "cinta métrica"],
                ["werkbank", "banco de trabajo"]
            ],
            "indoor": [
                ["schroevendraaier", "destornillador"],
                ["tang", "alicate / pinza"],
                ["moersleutel", "llave inglesa / llave fija"],
                ["inbussleutel", "llave Allen / llave hexagonal"],
                ["plug", "enchufe / clavija"],
                ["lamp", "lámpara"],
                ["stopcontact", "tomacorriente / enchufe"],
                ["verfroller", "rodillo de pintura"],
                ["kwast", "brocha / pincel"],
                ["meetlint", "cinta métrica"],
                ["waterpas", "nivel / nivel de burbuja"],
                ["stofzuiger", "aspiradora"]
            ],
            "outdoor": [
                ["grasmaaier", "cortacésped / podadora de césped"],
                ["hark", "rastrillo"],
                ["schep", "pala"],
                ["tuinslang", "manguera de jardín"],
                ["zaag", "sierra"],
                ["hamer", "martillo"],
                ["spade", "azada / pala grande"],
                ["kruiwagen", "carretilla"],
                ["snoeischaar", "tijeras de podar"],
                ["tuinborstel", "escoba de jardín"],
                ["tuinbank", "banco de jardín"],
                ["schop", "pala pequeña"]
            ],
            "heavy_equipment": [
                ["graafmachine", "excavadora"],
                ["bulldozer", "buldócer"],
                ["kraan", "grúa"],
                ["tractor", "tractor"],
                ["vrachtwagen", "camión"],
                ["roller", "compactadora / rodillo compactador"],
                ["dumptruck", "volquete / camión volquete"],
                ["shovel", "cargadora / pala cargadora"],
                ["betonmixer", "hormigonera / mezcladora de cemento"],
                ["hoogwerker", "plataforma elevadora / elevador de altura"],
                ["asfaltmachine", "extendedora de asfalto"],
                ["heftruck", "montacargas / forklift"]
            ],

    "planets": [
                ["planeet", "planeta"],
                ["zon", "sol"],
                ["maan", "luna"],
                ["Mercurius", "Mercurio"],
                ["Venus", "Venus"],
                ["Aarde", "Tierra"],
                ["Mars", "Marte"],
                ["Jupiter", "Júpiter"],
                ["Saturnus", "Saturno"],
                ["Uranus", "Urano"],
                ["Neptunus", "Neptuno"],
                ["Pluto", "Plutón"]
            ],
            "stars": [
                ["ster", "estrella"],
                ["sterrenbeeld", "zodíaco / constelación"],
                ["Melkweg", "Vía Láctea"],
                ["helder", "brillante"],
                ["vallende ster", "estrella fugaz"],
                ["nova", "nova"],
                ["supernova", "supernova"],
                ["zwarte gat", "agujero negro"],
                ["constellatie", "constelación"],
                ["poolster", "estrella polar / Polaris"],
                ["Sirius", "Sirio"],
                ["Orion", "Orión"]
            ],
            "zodiac": [
                ["Ram", "Aries"],
                ["Stier", "Tauro"],
                ["Tweelingen", "Géminis"],
                ["Kreeft", "Cáncer"],
                ["Leeuw", "Leo"],
                ["Maagd", "Virgo"],
                ["Weegschaal", "Libra"],
                ["Schorpioen", "Escorpio"],
                ["Boogschutter", "Sagitario"],
                ["Steenbok", "Capricornio"],
                ["Waterman", "Acuario"],
                ["Vissen", "Piscis"]
            ],
            "officials": [
                ["president", "presidente"],
                ["minister", "ministro"],
                ["parlement", "parlamento"],
                ["premier", "primer ministro"],
                ["burgemeester", "alcalde"],
                ["gouverneur", "gobernador"],
                ["ambtenaar", "funcionario público"],
                ["diplomaat", "diplomático"],
                ["rechter", "juez"],
                ["politiechef", "jefe de policía"],
                ["senator", "senador"],
                ["parlementslid", "diputado / miembro del parlamento"]
            ],
            "stadhuis": [
                ["stadhuis", "ayuntamiento / casa consistorial"],
                ["gemeente", "ayuntamiento / gobierno municipal"],
                ["burgemeester", "alcalde"],
                ["raadszaal", "sala de sesiones del consejo"],
                ["burgerzaken", "oficina de registro civil / padrón municipal"],
                ["trouwzaal", "sala de bodas civiles"],
                ["vergunning", "permiso / licencia"],
                ["belasting", "impuestos municipales"],
                ["paspoort", "pasaporte"],
                ["identiteitskaart", "DNI / tarjeta de identidad"],
                ["archief", "archivo"],
                ["loket", "ventanilla / mostrador de atención"]
            ],
            "politieburo": [
                ["politiebureau", "comisaría de policía"],
                ["politieagent", "agente de policía / policía"],
                ["commissaris", "comisario"],
                ["aangifte", "denuncia"],
                ["verhoor", "interrogatorio"],
                ["handboeien", "esposas"],
                ["patrouille", "patrulla"],
                ["arrestatie", "arresto / detención"],
                ["proces-verbaal", "acta policial / atestado"],
                ["getuige", "testigo"],
                ["verdachte", "sospechoso"],
                ["slachtoffer", "víctima"]
            ],

    "kerk": [
                ["kerk", "iglesia"],
                ["priester", "sacerdote / pastor"],
                ["mis", "misa"],
                ["preek", "sermón / prédica"],
                ["altaar", "altar"],
                ["kruis", "cruz"],
                ["bijbel", "Biblia"],
                ["doop", "bautismo"],
                ["huwelijk", "matrimonio eclesiástico"],
                ["begrafenis", "entierro / funeral en iglesia"],
                ["koor", "coro"],
                ["klok", "campana de iglesia"]
            ],
            "islam": [
                ["moskee", "mezquita"],
                ["gebed", "oración / salat"],
                ["ramadan", "ramadán"],
                ["vasten", "ayuno"],
                ["koran", "Corán / Al-Qur'an"],
                ["profeet", "profeta"],
                ["mecca", "La Meca"],
                ["hadj", "hajj / peregrinación a La Meca"],
                ["imam", "imán"],
                ["azaan", "azan / llamada a la oración"],
                ["vrijdaggebed", "oración del viernes / salat Jumat"],
                ["zakat", "zakat / limosna obligatoria"]
            ],
            "protestantism": [
                ["protestants", "protestante"],
                ["kerk", "iglesia"],
                ["predikant", "predicador / pastor protestante"],
                ["bijbel", "Biblia"],
                ["preek", "sermón"],
                ["dopen", "bautismo"],
                ["avondmaal", "Santa Cena / comunión"],
                ["psalm", "salmo"],
                ["zondagsschool", "escuela dominical"],
                ["hervorming", "Reforma"],
                ["calvinisme", "calvinismo"],
                ["lutheranisme", "luteranismo"]
            ],
            "catholicism": [
                ["katholiek", "católico"],
                ["paus", "papa"],
                ["mis", "misa"],
                ["priester", "sacerdote / cura"],
                ["biecht", "confesión"],
                ["communie", "comunión"],
                ["doop", "bautismo"],
                ["heilige", "santo / santa"],
                ["kruis", "cruz"],
                ["rozenkrans", "rosario"],
                ["klooster", "monasterio / convento"],
                ["kathedraal", "catedral"]
            ],
            "hinduism": [
                ["hindoe", "hindú"],
                ["dharma", "dharma"],
                ["karma", "karma"],
                ["reïncarnatie", "reencarnación"],
                ["tempel", "templo / pura"],
                ["god", "dios"],
                ["goddess", "diosa"],
                ["ganesha", "Ganesha"],
                ["shiva", "Shiva"],
                ["vishnu", "Vishnu"],
                ["brahma", "Brahma"],
                ["puja", "puja / adoración"]
            ],
            "buddhism": [
                ["boeddhisme", "budismo"],
                ["boeddha", "Buda"],
                ["dharma", "dharma"],
                ["nirvana", "nirvana"],
                ["meditatie", "meditación"],
                ["tempel", "templo / vihara"],
                ["monnik", "monje"],
                ["non", "monja"],
                ["karma", "karma"],
                ["vier edele waarheden", "cuatro nobles verdades"],
                ["achtvoudig pad", "óctuple sendero"],
                ["boeddha-beeld", "estatua de Buda"]
            ],

    "confucianism": [
                ["confucianisme", "confucianismo"],
                ["Confucius", "Confucio"],
                ["filosofie", "filosofía"],
                ["harmonie", "armonía"],
                ["respect", "respeto"],
                ["familie", "familia"],
                ["plicht", "deber / obligación"],
                ["wijsheid", "sabiduría"],
                ["ritueel", "ritual / ceremonia"],
                ["leraar", "maestro"],
                ["moreel", "moral"],
                ["deugd", "virtud"]
            ],
            "pc": [
                ["computer", "computadora / ordenador"],
                ["laptop", "portátil / laptop"],
                ["desktop", "computadora de escritorio"],
                ["toetsenbord", "teclado"],
                ["muis", "ratón"],
                ["scherm", "pantalla / monitor"],
                ["processor", "procesador"],
                ["geheugen", "memoria / RAM"],
                ["harde schijf", "disco duro"],
                ["besturingssysteem", "sistema operativo"],
                ["internet", "internet"],
                ["software", "software / programa"]
            ],
            "audio": [
                ["geluid", "sonido"],
                ["luidspreker", "altavoz / parlante"],
                ["headset", "auriculares con micrófono / headset"],
                ["microfoon", "micrófono"],
                ["hoofdtelefoon", "auriculares / headphones"],
                ["versterker", "amplificador"],
                ["subwoofer", "subwoofer"],
                ["soundbar", "barra de sonido"],
                ["mp3", "mp3"],
                ["streaming", "streaming"],
                ["podcast", "podcast"],
                ["geluidskaart", "tarjeta de sonido"]
            ],
            "video": [
                ["video", "video"],
                ["camera", "cámara"],
                ["film", "película"],
                ["streaming", "streaming"],
                ["YouTube", "YouTube"],
                ["Netflix", "Netflix"],
                ["resolutie", "resolución"],
                ["4K", "4K"],
                ["HD", "HD"],
                ["editen", "editar"],
                ["uploaden", "subir / cargar"],
                ["downloaden", "descargar"]
            ],
            "zeilen": [
                ["zeilen", "navegar a vela"],
                ["zeilboot", "velero / barco de vela"],
                ["zeil", "vela"],
                ["mast", "mástil"],
                ["schoot", "escota / cabo de vela"],
                ["wind", "viento"],
                ["koers", "rumbo / curso"],
                ["haven", "puerto"],
                ["ankeren", "anclar"],
                ["kiel", "quilla"],
                ["spinnaker", "spinnaker"],
                ["jacht", "yate"]
            ],
            "boot": [
                ["boot", "barco / bote"],
                ["roeiboot", "bote de remos"],
                ["speedboot", "lancha rápida"],
                ["motorboot", "barco a motor"],
                ["kano", "canoa"],
                ["kajak", "kayak"],
                ["roer", "timón"],
                ["dek", "cubierta"],
                ["cabine", "camarote / cabina"],
                ["anker", "ancla"],
                ["reddingsvest", "chaleco salvavidas"],
                ["brandstof", "combustible"]
            ],
            "zee_oceaan": [
                ["zee", "mar"],
                ["oceaan", "océano"],
                ["strand", "playa"],
                ["golf", "ola"],
                ["getijde", "marea"],
                ["stroming", "corriente"],
                ["duiken", "bucear"],
                ["zwemmen", "nadar"],
                ["vissen", "pescar"],
                ["schelp", "concha / caracol marino"],
                ["zout water", "agua salada"],
                ["koraal", "coral"]
            ],

            }
    };